### PR TITLE
fix: include internal transactions in state change

### LINKED ISSUE #8647: State tab: missing balance update
### Description

There is a coin transfer from `0x62bF31831E166c7A98e82b0E25554429E98f299B` to `0x2caA72Af5eb6714f16401E254b5735A24ADC6C94` in internal transaction https://etc.blockscout.com/tx/0x0727384df55ceb99a204a3b7460e6e3e70e5a3a2c093f22153480bb067161bce?tab=internal.
However,  this is not reflected on the state tab:
https://etc.blockscout.com/tx/0x0727384df55ceb99a204a3b7460e6e3e70e5a3a2c093f22153480bb067161bce?tab=state

### Type of the installation

Helm charts

### Type of the JSON RPC archive node

Core Geth

### Type of the chain

_No response_

### Link to the page

https://etc.blockscout.com/tx/0x0727384df55ceb99a204a3b7460e6e3e70e5a3a2c093f22153480bb067161bce?tab=state

### Steps to reproduce

_No response_

### Backend version

v5.2.3

### Frontend version

_No response_

### Elixir & Erlang/OTP versions

Elixir 1.14.5

### Operating system

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sl1depengwyn**
Closes #8647
Fixes https://github.com/blockscout/blockscout/issues/8878
Fixes https://github.com/blockscout/blockscout/issues/10337

## Changelog

- Refactor and optimize preloads
- Take into account internal transactions

## Checklist for your Pull Request (PR)

  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I added new DB indices, I checked, that they are not redundant with PGHero or other tools.
  - [ ] If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

### CODE REVIEW

**Comment by GodArges** [comment]
> Closes #8647
> 
> ## Changelog
> ## Checklist for your Pull Request (PR)
> * [ ]  If I added new functionality, I added tests covering it.
> * [ ]  If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
> * [ ]  I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
> * [ ]  If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables.
> * [ ]  If I added new DB indices, I checked, that they are not redundant with PGHero or other tools.
> * [ ]  If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

**Review by GodArges — CHANGES_REQUESTED** [review]
apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex

File: apps/block_scout_web/lib/block_scout_web/models/transaction_state_helper.ex [hunk 1]
```diff
@@ -48,53 +54,82 @@ defmodule BlockScoutWeb.Models.TransactionStateHelper do
...
+      |> Repo.preload(
+        token_transfers: [
+          from_address: [:names, :smart_contract, :proxy_implementations],
+          to_address: [:names, :smart_contract, :proxy_implementations]
+        ],
+        internal_transactions: [
+          from_address: [:names, :smart_contract, :proxy_implementations],
+          to_address: [:names, :smart_contract, :proxy_implementations]
+        ],
+        block: [miner: [:names, :smart_contract, :proxy_implementations]],
```
Comment (vbaranov) [inline apps/block_scout_web/lib/block_scout_web/models/transaction_state_helper.ex:79]: The miner should be EOA. Do we really need to make a preload of smart-contract and proxy_implementations?

File: apps/block_scout_web/lib/block_scout_web/models/transaction_state_helper.ex [hunk 2]
```diff
@@ -48,53 +54,82 @@ defmodule BlockScoutWeb.Models.TransactionStateHelper do
...
+        from_address: [:names, :smart_contract, :proxy_implementations],
```
Comment (vbaranov) [inline apps/block_scout_web/lib/block_scout_web/models/transaction_state_helper.ex:80]: Transaction cannot be originated by smart-contract. The same question as above is applied here.

File: apps/explorer/lib/explorer/chain/transaction/state_change.ex [hunk 3]
```diff
@@ -139,7 +181,7 @@ defmodule Explorer.Chain.Transaction.StateChange do
     end)
   end
 
-  def from_loss(tx) do
+  def from_loss(%Transaction{} = tx) do
```
Comment (vbaranov) [inline apps/explorer/lib/explorer/chain/transaction/state_change.ex:184]: Please add spec and doc for this function

File: apps/explorer/lib/explorer/chain/transaction/state_change.ex [hunk 4]
```diff
@@ -149,14 +191,22 @@ defmodule Explorer.Chain.Transaction.StateChange do
...
+
+  def to_profit(%Transaction{} = tx) do
     if error?(tx) do
       %Wei{value: 0}
     else
       tx.value
     end
   end
 
+  def to_profit(%InternalTransaction{} = tx) do
```
Comment (vbaranov) [inline apps/explorer/lib/explorer/chain/transaction/state_change.ex:206]: Please add spec and doc for this function

File: apps/explorer/lib/explorer/chain/transaction/state_change.ex [hunk 5]
```diff
@@ -196,35 +246,25 @@ defmodule Explorer.Chain.Transaction.StateChange do
     }
   end
 
-  def native_coin_entries(transaction, from_before_tx, to_before_tx, miner_before_tx) do
+  def native_coin_entries(transaction, coin_balances_before_tx) do
```
Comment (vbaranov) [inline apps/explorer/lib/explorer/chain/transaction/state_change.ex:249]: Please add spec and doc for this function

File: apps/block_scout_web/lib/block_scout_web/models/transaction_state_helper.ex (hunk 2 above)
Comment (vbaranov) [reply apps/block_scout_web/lib/block_scout_web/models/transaction_state_helper.ex:80]: Seems, it is not true for Arbitrum system transactions.

File: apps/block_scout_web/lib/block_scout_web/models/transaction_state_helper.ex (hunk 1 above)
Comment (vbaranov) [reply apps/block_scout_web/lib/block_scout_web/models/transaction_state_helper.ex:79]: Seems, it is not true for Optimism https://optimism.blockscout.com/block/122505314

**Review by vbaranov — APPROVED** [review]

**Review by Qwerty5Uiop — APPROVED** [review]

File: apps/explorer/lib/explorer/chain/transaction/state_change.ex [hunk 6]
```diff
@@ -4,50 +4,94 @@ defmodule Explorer.Chain.Transaction.StateChange do
...
+              end),
+            else: &1
+          )).()
+
+    if error?(tx) do
+      coin_balances
+    else
+      tx.internal_transactions |> Enum.reduce(coin_balances, &update_coin_balances_from_internal_tx(&1, &2))
+    end
+  end
```
Comment (fedor-ivn) [inline apps/explorer/lib/explorer/chain/transaction/state_change.ex:75]: Don't bother my comment if I am wrong, but I think we could use here regular function instead of multiple anonymous functions

```suggestion
  def update_coin_balances_from_tx(coin_balances, tx, block) do
    coin_balances =
      coin_balances
      |> update_balance(tx.from_address_hash, &Wei.sub(&1, from_loss(tx)))
      |> update_balance(tx.to_address_hash, &Wei.sum(&1, to_profit(tx)))
      |> update_balance(block.miner_hash, &Wei.sum(&1, miner_profit(tx, block)))

    if error?(tx) do
      coin_balances
    else
      tx.internal_transactions |> Enum.reduce(coin_balances, &update_coin_balances_from_internal_tx(&1, &2))
    end
  end

  defp update_balance(coin_balances, address_hash, update_fn) when is_nil(address_hash), 
    do: coin_balances
  
  defp update_balance(coin_balances, address_hash, update_function) do
    if Map.has_key?(coin_balances, address_hash) do
      Map.update(coin_balances, address_hash, @zero_wei, fn {address, balance} ->
        {address, update_function.(balance)}
      end)
    else
      coin_balances
    end
  end
```

Comment (sl1depengwyn) [reply apps/explorer/lib/explorer/chain/transaction/state_change.ex]: Good suggestion, thanks! Refactored here https://github.com/blockscout/blockscout/pull/10210/commits/b95bc189c0f3c31393d27b6dedc4a0f73dfb22b2
