### PR TITLE
fix: Replace tx gas_price with effectiveGasPrice from receipt

### LINKED ISSUE #9730: Handle `effectiveGasPrice` from tx receipt
According to [ethereum docs](https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_gettransactionreceipt), `effectiveGasPrice` in `eth_getTransactionReceipt` is amount of paid fees. But `gasPrice` in `eth_getTransactionByHash` is gas price provided by sender, and it could be changed

### PR DESCRIPTION
**Pull request by nikitosing**
Closes #9730 

## Changelog
- Replace tx gas_price with effectiveGasPrice from receipt

## Checklist for your Pull Request (PR)

  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

### CODE REVIEW

**Review by sl1depengwyn — APPROVED** [review]

File: apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex [hunk 1]
```diff
@@ -170,8 +171,15 @@ defmodule EthereumJSONRPC.Receipt do
       transaction_hash: transaction_hash,
       transaction_index: transaction_index
     }
+    |> maybe_append_gas_price(elixir)
   end
 
+  defp maybe_append_gas_price(params, %{"effectiveGasPrice" => effective_gas_price}) do
```
Comment (vbaranov) [inline apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex:177]: After this change do we still need `def effective_gas_price/1`, which is used as a fallback when transaction.gas_price is nil?

Comment (k1rill-fedoseev) [inline apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex:177]: Reportedly, there are some problems with effectiveGasPrice in zkEVM JSON RPC - https://github.com/0xPolygonHermez/zkevm-node/issues/3420

I think it might be the case for some other L2s as well.

Maybe it makes sense to use `effectiveGasPrice` value if it's non-zero, otherwise fallback to the value of `gasPrice`. If both fields are missing or zeros, then save 0 or nil as gas price.

Comment (nikitosing) [reply apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex:177]: But how could we distinguish between cases when effectiveGasPrice is actually zero? I'd prefer not to add such check. In my opinion we should trust a node.

Comment (nikitosing) [reply apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex:177]: I think it still can be useful for abstract cases when for some reasons effectiveGasPrice is missed in tx receipt or it's null

**Comment by varasev** [comment]
This should overwrite `gas_price` already taken from `eth_getTransactionByHash` here https://github.com/blockscout/blockscout/blob/da5575d4e0cef9b7cac8deab7529fc8134508d71/apps/indexer/lib/indexer/block/fetcher/receipts.ex#L46, correct?

**Comment by nikitosing** [comment]
> This should overwrite `gas_price` already taken from `eth_getTransactionByHash` here
> 
> https://github.com/blockscout/blockscout/blob/da5575d4e0cef9b7cac8deab7529fc8134508d71/apps/indexer/lib/indexer/block/fetcher/receipts.ex#L46
> 
> , correct?
@varasev 
Yes, correct!

**Review by varasev — APPROVED** [review]

**Review by k1rill-fedoseev — APPROVED** [review]
