### PR TITLE
fix: on demand bytecode fetcher for eip7702 addresses

### LINKED ISSUE #12309: Code field on EOA not updating after initial contract address set (Pectra upgrade, Sepolia)
### Description

When interacting with the Pectra upgrade on the Ethereum Sepolia testnet, I encountered an issue where the code field on an EOA (Externally Owned Account) with code fails to update properly on Blockscout.

Specifically:

Initially, I set a contract address for the code field on my EOA. This appeared and resolved correctly.

However, when I updated the code contract address, Blockscout continued to reference the original contract address. The explorer fails to reflect the updated contract address, and the code field does not change.

Image

But it gets updated on other explorer.

Image

This seems like an explorer-side caching or indexing issue that ignores contract address updates on EOAs with code (common in Pectra-style patterns).

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth (Ethereum Sepolia archive node)

### Type of the chain

L1

### Link to the page

_No response_

### Steps to reproduce

- Deploy a contract and set it as code on an EOA using the Pectra pattern.

- Blockscout will correctly show the contract address and code.

- Update the code field by assigning a different contract address to the same EOA.

- Refresh the page or revisit later — Blockscout still shows the initial contract, ignoring the new one.

Expected behavior: The code field should update to the new contract address as stored on chain.

### Backend version

v8.0.1

### Frontend version

_No response_

### Elixir & Erlang/OTP versions

Elixir 1.17.3

### Operating system

WSL

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by k1rill-fedoseev**
Closes #12309 , partially addresses #12108

### Enhancements

* automatically update proxy_implementations for eip7702 address, don't rely on on-demand proxy logic

### Bug Fixes

* fix on-demand bytecode fetcher for eip7702 addresses

## Checklist for your Pull Request (PR)

- [X] If I added new functionality, I added tests covering it.
- [X] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
- [ ] I checked whether I should update the docs and did so by submitting a PR to [docs repository](https://github.com/blockscout/docs).
- [ ] If I added/changed/removed ENV var, I submitted a PR to [docs repository](https://github.com/blockscout/docs) to update the list of [env vars](https://github.com/blockscout/docs/blob/master/setup/env-variables/README.md) and I updated the version to `master` in the Version column. If I removed variable, I added it to [Deprecated ENV Variables](https://github.com/blockscout/docs/blob/master/setup/env-variables/deprecated-env-variables/README.md) page. After merging docs PR, changes will be reflected in these [pages](https://docs.blockscout.com/setup/env-variables).
- [ ] If I added new DB indices, I checked, that they are not redundant, with PGHero or other tools.
- [ ] If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

## Summary by CodeRabbit

- **New Features**
  - Added the ability to delete all proxy implementation records for a given address.
  - Enhanced contract code fetching to handle EIP-7702 proxies, including updating or deleting proxy implementation data based on fetched code.

- **Bug Fixes**
  - Corrected the logic for conflict resolution when inserting contract code, ensuring proper handling of contract code updates.

- **Tests**
  - Added tests to verify contract code updates and proxy implementation handling for EIP-7702 addresses.

- **Refactor**
  - Improved contract code fetching logic to better handle externally owned accounts (EOAs) with code and updated retry conditions.
  - Adjusted the order of proxy pattern checks to optimize implementation detection.

- **Chores**
  - Removed unused aliases and updated type specifications for clarity and maintainability.

### CODE REVIEW

File: apps/explorer/lib/explorer/chain/import/runner/addresses.ex [hunk 1]
```diff
@@ -232,7 +232,7 @@ defmodule Explorer.Chain.Import.Runner.Addresses do
       # where any of `set`s would make a change
       # This is so that tuples are only generated when a change would occur
       where:
-        fragment("COALESCE(?, EXCLUDED.contract_code) IS DISTINCT FROM ?", address.contract_code, address.contract_code) or
+        fragment("COALESCE(EXCLUDED.contract_code, ?) IS DISTINCT FROM ?", address.contract_code, address.contract_code) or
```
Comment (k1rill-fedoseev) [inline apps/explorer/lib/explorer/chain/import/runner/addresses.ex:235]: Doesn't impact current PR, but I think this was a bug, and fragment here should always match the fragment above we're trying to insert (in line 204)

File: apps/explorer/lib/explorer/chain/smart_contract/proxy.ex [hunk 2]
```diff
@@ -201,8 +201,8 @@ defmodule Explorer.Chain.SmartContract.Proxy do
     functions =
       [
         :get_implementation_address_hash_string_eip1167,
-        :get_implementation_address_hash_string_clones_with_immutable_arguments,
         :get_implementation_address_hash_string_eip7702,
+        :get_implementation_address_hash_string_clones_with_immutable_arguments,
```
Comment (k1rill-fedoseev) [inline apps/explorer/lib/explorer/chain/smart_contract/proxy.ex:205]: I expect we would have more 7702 proxies than clones, but less 7702 proxies than 1167, so it makes sense to reorder them as such to reduce "expected value" of work done each time.

File: apps/indexer/test/indexer/fetcher/on_demand/contract_code_test.exs [hunk 3]
```diff
@@ -191,6 +194,82 @@ defmodule Indexer.Fetcher.OnDemand.ContractCodeTest do
...
+
+          assert proxy_implementations.proxy_address_hash == address_hash
+          assert proxy_implementations.proxy_type == :eip7702
+          assert proxy_implementations.address_hashes == implementations
+          assert proxy_implementations.names == [nil]
+        end
+      end)
+
+      default_threshold = parse_time_env_var("CONTRACT_CODE_ON_DEMAND_FETCHER_THRESHOLD", "5s")
+      Application.put_env(:indexer, ContractCodeOnDemand, threshold: default_threshold)
```
Comment (fedor-ivn) [inline apps/indexer/test/indexer/fetcher/on_demand/contract_code_test.exs:270]: nitpick: in other test cases, we prefer to define configuration overrides within the `on_exit/2` callback.

File: apps/indexer/lib/indexer/fetcher/on_demand/contract_code.ex [hunk 4]
```diff
@@ -106,17 +110,37 @@ defmodule Indexer.Fetcher.OnDemand.ContractCode do
...
+            # TODO: it's better to use a generic code like this, but it does unnecessary minimal proxy checks and DB lookups
+            # Address.eoa_with_code?(new_address) ->
+            #   Proxy.fetch_implementation_address_hash(address.hash, [], [])
+
+            delegate = EIP7702.get_delegate_address(fetched_code.bytes) ->
+              Implementation.save_implementation_data([delegate |> to_string()], address.hash, :eip7702, [])
+
+            true ->
+              :ok
+          end
```
Comment (fedor-ivn) [inline apps/indexer/lib/indexer/fetcher/on_demand/contract_code.ex:137]: If one of these queries fails, could that introduce data inconsistencies? Is it safe to execute these operations independently without wrapping into a single transaction?

Comment (k1rill-fedoseev) [reply apps/indexer/lib/indexer/fetcher/on_demand/contract_code.ex:137]: Records in `proxy_implementations` should be updated once in a while on-demand anyway, so these queries just speed up this process for better UI/UX. I think if `Implementation.delete_implementations` or `Implementation.save_implementation_data` would fail, it's still better to commit `Addresses.insert` changes, than commit nothing.

Comment (fedor-ivn) [reply apps/indexer/lib/indexer/fetcher/on_demand/contract_code.ex:137]: Got it, thanks for explaining on this

**Review by fedor-ivn — APPROVED** [review]

File: apps/indexer/lib/indexer/fetcher/on_demand/contract_code.ex [hunk 5]
```diff
@@ -106,17 +110,37 @@ defmodule Indexer.Fetcher.OnDemand.ContractCode do
             )},
          contract_code_object = List.first(fetched_codes),
          false <- is_nil(contract_code_object),
-         true <- contract_code_object.code !== "0x" do
-      case Chain.import(%{addresses: %{params: [%{hash: address.hash, contract_code: contract_code_object.code}]}}) do
+         {:ok, fetched_code} <-
+           (contract_code_object.code == "0x" && {:ok, nil}) || Data.cast(contract_code_object.code),
+         true <- fetched_code != address.contract_code do
+      case Addresses.insert(Repo, [%{hash: address.hash, contract_code: fetched_code}], %{
```
Comment (vbaranov) [inline apps/indexer/lib/indexer/fetcher/on_demand/contract_code.ex:116]: Changing from Chain.import/1 to Addresses.insert/2 means the on-demand fetcher will no longer populate the Multichain service DB. Just curious—what was the reason for switching to this approach?

File: apps/indexer/lib/indexer/fetcher/on_demand/contract_code.ex [hunk 6]
```diff
@@ -106,17 +110,37 @@ defmodule Indexer.Fetcher.OnDemand.ContractCode do
...
+             timeout: :infinity,
```
Comment (vbaranov) [inline apps/indexer/lib/indexer/fetcher/on_demand/contract_code.ex:117]: Will an infinite timeout potentially cause hanging of the on-demand trigger? `Chain.import` uses a [finite 4-minute](https://github.com/blockscout/blockscout/blob/e071644931f07ffbfd66349208602befd3651229/apps/explorer/lib/explorer/chain/import.ex#L134) timeout.

File: apps/indexer/lib/indexer/fetcher/on_demand/contract_code.ex [hunk 7]
```diff
@@ -106,17 +110,37 @@ defmodule Indexer.Fetcher.OnDemand.ContractCode do
...
+          cond do
+            is_nil(fetched_code) ->
+              Implementation.delete_implementations(address.hash)
+
+            # TODO: it's better to use a generic code like this, but it does unnecessary minimal proxy checks and DB lookups
+            # Address.eoa_with_code?(new_address) ->
+            #   Proxy.fetch_implementation_address_hash(address.hash, [], [])
+
+            delegate = EIP7702.get_delegate_address(fetched_code.bytes) ->
+              Implementation.save_implementation_data([delegate |> to_string()], address.hash, :eip7702, [])
```
Comment (vbaranov) [inline apps/indexer/lib/indexer/fetcher/on_demand/contract_code.ex:133]: Should we call `save_implementation_data/4`, if `get_delegate_address/1` returns nil?

File: apps/indexer/lib/indexer/fetcher/on_demand/contract_code.ex [hunk 8]
```diff
@@ -106,17 +110,37 @@ defmodule Indexer.Fetcher.OnDemand.ContractCode do
...
+             timeout: :infinity,
+             on_conflict: {:replace, [:contract_code, :updated_at]},
+             timestamps: Import.timestamps()
+           }) do
         {:ok, _} ->
+          # Update EIP7702 proxy addresses to avoid inconsistencies between addresses and proxy_implementations tables.
+          # Other proxy types are not handled here, since their bytecode doesn't change the way EIP7702 bytecode does.
+          cond do
+            is_nil(fetched_code) ->
+              Implementation.delete_implementations(address.hash)
```
Comment (vbaranov) [inline apps/indexer/lib/indexer/fetcher/on_demand/contract_code.ex:126]: Is it safe not to check explicitly that the address is EOA with code via `eoa_with_code?/1` before deletion of implementations?

File: apps/indexer/lib/indexer/fetcher/on_demand/contract_code.ex (hunk 5 above)
Comment (k1rill-fedoseev) [reply apps/indexer/lib/indexer/fetcher/on_demand/contract_code.ex]: There was a problem with setting contract_code to nil, due to `should_update?` implementation in `Chain.import/1`. But seems like I found a workaround for now, so we can keep it. Fixed in b8210c3

File: apps/indexer/lib/indexer/fetcher/on_demand/contract_code.ex (hunk 6 above)
Comment (k1rill-fedoseev) [reply apps/indexer/lib/indexer/fetcher/on_demand/contract_code.ex]: Fixed in https://github.com/blockscout/blockscout/commit/b8210c3a6de11c220a4e3757614bcd4523e7ab59

File: apps/indexer/lib/indexer/fetcher/on_demand/contract_code.ex (hunk 8 above)
Comment (k1rill-fedoseev) [reply apps/indexer/lib/indexer/fetcher/on_demand/contract_code.ex:129]: Should not happen, but added an extra check only for EIP7702 contracts. Fixed in b0db209

File: apps/indexer/lib/indexer/fetcher/on_demand/contract_code.ex (hunk 7 above)
Comment (k1rill-fedoseev) [reply apps/indexer/lib/indexer/fetcher/on_demand/contract_code.ex:136]: We shouldn't, but `cond` block won't execute this branch in this case, since `nil` isn't a "truthy" value

**Review by vbaranov — APPROVED** [review]
