### PR TITLE
fix: Allow fetching of stale token balances

### LINKED ISSUE #14153: Token balance fetcher does not update balances
When an address receives or sends a token it already holds, its token balance does not automatically update. It is only updated if the on-demand fetcher is triggered.
The issue was introduced by #13923 in version [`v10.0.0`](https://github.com/blockscout/blockscout/releases/tag/v10.0.0)

### PR DESCRIPTION
**Pull request by GimluCom**
Fixes #14153

### Bug Fixes

This PR allows stale token balances to be updated.

## Checklist for your Pull Request (PR)

- [ ] I verified this PR does not break any public APIs, contracts, or interfaces that external consumers depend on.
- [ ] If I added new functionality, I added tests covering it.
- [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
- [ ] I updated documentation if needed:
  - [ ] General docs: submitted PR to [docs repository](https://github.com/blockscout/docs).
  - [ ] ENV vars: updated [env vars list](https://github.com/blockscout/docs/tree/main/setup/env-variables) and set version parameter to `master`.
  - [ ] Deprecated vars: added to [deprecated env vars list](https://github.com/blockscout/docs/tree/main/setup/env-variables/deprecated-env-variables).
- [ ] If I modified API endpoints, I updated the Swagger/OpenAPI schemas accordingly and checked that schemas are asserted in tests, and highlighted the change in the PR description.
- [ ] If I added new DB indices, I checked, that they are not redundant, with PGHero or other tools.
- [ ] If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved import logic for address token balances so updates no longer get skipped when incoming timestamps are missing. Updates now better preserve existing values when incoming amounts are absent, and only overwrite balances for newer or sufficiently complete incoming data. Result: more accurate, consistent balance information after imports.

### CODE REVIEW

File: apps/explorer/lib/explorer/chain/import/runner/address/current_token_balances.ex [hunk 1]
```diff
@@ -298,7 +298,9 @@ defmodule Explorer.Chain.Import.Runner.Address.CurrentTokenBalances do
   defp should_update?(_new_ctb, nil), do: true
 
   # new ctb has no value
-  defp should_update?(%{value_fetched_at: nil}, _existing_ctb), do: false
+  defp should_update?(%{value_fetched_at: fetched_at, value: nil}, _existing_ctb)
```
Comment (Qwerty5Uiop) [inline apps/explorer/lib/explorer/chain/import/runner/address/current_token_balances.ex]: In what case is it possible that the balance will have `value_fetched_at` and not the `value`? Seems like we don't really need this clause

**Review by Qwerty5Uiop — APPROVED** [review]

File: apps/explorer/lib/explorer/chain/import/runner/address/current_token_balances.ex (hunk 1 above)
Comment (GimluCom) [reply apps/explorer/lib/explorer/chain/import/runner/address/current_token_balances.ex]: Removed the clause

**Comment by vbaranov** [comment]
@GimluCom Nice catch, thank you!
