### PR TITLE
fix: update `ex_abi` to fix type decoder for huge lists

### LINKED ISSUE #10292: Handle huge number of list items while ABI decoding
Currently, if ABI contains, let's say, array of tuples, and it decodes the length of the array as number _n_ where n * 32 bytes > the length of the input, we shouldn't process such decoding in order to prevent OOM issues, which could arise, if _n_ is a huge number.

### PR DESCRIPTION
**Pull request by fedor-ivn**
## Motivation

Closes #10292.

### Enhancements
*Things you added that don't break anything.  Regression tests for Bug Fixes count as Enhancements.*

### Bug Fixes
*Things you changed that fix bugs.  If a fixes a bug, but in so doing adds a new requirement, removes code, or requires a database reset and reindex, the breaking part of the change should be added to Incompatible Changes below also.*

## Checklist for your Pull Request (PR)

  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I added new DB indices, I checked, that they are not redundant with PGHero or other tools.
  - [ ] If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

### CODE REVIEW

File: apps/ethereum_jsonrpc/mix.exs [hunk 1]
```diff
@@ -77,7 +77,8 @@ defmodule EthereumJsonrpc.MixProject do
       # Convert unix timestamps in JSONRPC to DateTimes
       {:timex, "~> 3.7.1"},
       # Encode/decode function names and arguments
-      {:ex_abi, "~> 0.4"},
+      # {:ex_abi, "~> 0.4"},
+      {:ex_abi, git: "https://github.com/fedor-ivn/ex_abi", branch: "fix-type-decoder-huge-lists", override: true},
```
Comment (vbaranov) [inline apps/ethereum_jsonrpc/mix.exs:81]: Let's add a todo note, that we would like to return to the core repo once https://github.com/poanetwork/ex_abi/pull/170 is merged

Comment (fedor-ivn) [reply apps/ethereum_jsonrpc/mix.exs:82]: Sure, please see [320f97d](https://github.com/blockscout/blockscout/pull/10294/commits/320f97d8005b979e3f6ac0b434eca2061215d0db)

**Review by vbaranov — APPROVED** [review]

**Review by vbaranov — APPROVED** [review]
