### PR TITLE
BS api v2: smart contracts

### LINKED ISSUE #6571: Verified contract sender incorrect in "read contract" tab.
Verified contract sender incorrect in "read contract" tab.

### Environment

* Deployment type (Manual/Docker/Docker-compose):Manual
* Elixir & Erlang/OTP versions (`elixir -version`):Elixir 1.13.4 (compiled with Erlang/OTP 22)
* Node JS version (`node -v`):v16.15.0
* Operating System: Ubuntu
* Blockscout Version/branch/commit:v4.1.8 master
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):Geth

### Steps to reproduce

image
I deployed a contract,as above.Then I had Verified it. But when I open the "read contract" tab,all the read functions been invoke automatic,then I write a function to see which sender it use,It print "
0x0000000000000000000000000000000000000000".
How can I call read functions use my current connected wallet address?

### Expected behaviour

“read contract” should be call use my connected wallet address,Or let me call it manual,not automatic.

### Actual behaviour

“read contract” been call automatic,have not use my wallet address.

### PR DESCRIPTION
**Pull request by nikitosing**
Close #6571 

## Changelog
- add fetching of wallet address from MM before fetching read smart contract methods (can be fetched if you are logged in metamask)
- `/addresses/{address_hash}/tokens`
- `/v2/smart-contracts/{address_hash}`
- `/v2/smart-contracts/{address_hash}/methods-read` (+custom abi)
- `/v2/smart-contracts/{address_hash}/methods-write` (+custom abi)
- `/v2/smart-contracts/{address_hash}/methods-read-proxy`
- `/v2/smart-contracts/{address_hash}/methods-write-proxy`
- `/v2/smart-contracts/{address_hash}/query-read-method` (+custom abi)
- changed messages format in websockets: internal_transactions, token transfers, transactions
- now /addresses returns 404 if address is not in DB

## Checklist for your Pull Request (PR)

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

### CODE REVIEW

File: apps/block_scout_web/assets/js/lib/smart_contract/functions.js [hunk 1]
```diff
@@ -96,11 +96,19 @@ const readWriteFunction = (element) => {
 const container = $('[data-smart-contract-functions]')
 
 if (container.length) {
-  loadFunctions(container, false)
+  getCurrentAccountPromise(window.web3 && window.web3.currentProvider).then((currentAccount) => {
+    loadFunctions(container, false, currentAccount)
+  }, () => {
+    loadFunctions(container, false, null)
+  })
```
Comment (vbaranov) [inline apps/block_scout_web/assets/js/lib/smart_contract/functions.js:103]: @nikitosing let's define as function re-use here and in 109-113 lines?

**Review by sl1depengwyn — APPROVED** [review]

**Review by vbaranov — APPROVED** [review]
