### PR TITLE
Fix broken functions input

### LINKED ISSUE #4849: Broken render of function input
https://blockscout.com/xdai/mainnet/tx/0x604287cbf6cefeb9e4813d4887ffc408fd1f841d43f2327568731812e1efa15a/logs

image

### PR DESCRIPTION
**Pull request by nikitosing**
Close #4849 

### Bug Fixes
- If input too long and part of it hidden then we do not show addresses inside it as links
- Increase default value in case of bad integer in ENV: `0` -> `2040`

## Checklist for your Pull Request (PR)

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

### CODE REVIEW

File: apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex [hunk 1]
```diff
@@ -550,7 +550,7 @@ defmodule BlockScoutWeb.TransactionView do
 
     case Integer.parse(string_value) do
       {integer, ""} -> integer
-      _ -> 0
+      _ -> 2040
```
Comment (vbaranov) [inline apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex:553]: @nikitosing what is the intention to change the value?

Comment (nikitosing) [reply apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex:553]: I made it equal to the [default value](https://github.com/blockscout/blockscout/blob/master/apps/block_scout_web/config/config.exs#L53)

**Review by vbaranov — APPROVED** [review]
