### PR TITLE
fix: Fix search for ERC-1155 with null symbol

### LINKED ISSUE #8716: ERC-1155 token search doesn't work on Stability testnet
##Description

Search on Tokens page doesn't return any results for ERC-1155.

##Backend version

[v5.3.0-beta.+commit.cc24c2c4](https://github.com/blockscout/blockscout/commit/cc24c2c4)

##Links

Example:
https://stability-testnet.blockscout.com/tokens?q=test&type=ERC-1155

### PR DESCRIPTION
**Pull request by nikitosing**
Closes #8716 

## Changelog
- new `tokens_name_partial_fts_index`
- factored out repeated fts query for tokens to `Explorer.Chain.Token.apply_fts_filter/2`
## Checklist for your Pull Request (PR)

- [ ] I verified this PR does not break any public APIs, contracts, or interfaces that external consumers depend on.
- [ ] If I added new functionality, I added tests covering it.
- [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
- [ ] I updated documentation if needed:
  - [ ] General docs: submitted PR to [docs repository](https://github.com/blockscout/docs).
  - [ ] ENV vars: updated [env vars list](https://github.com/blockscout/docs/tree/main/setup/env-variables) and set version parameter to `master`.
  - [ ] Deprecated vars: added to [deprecated env vars list](https://github.com/blockscout/docs/tree/main/setup/env-variables/deprecated-env-variables).
- [ ] If I modified API endpoints, I updated the Swagger/OpenAPI schemas accordingly and checked that schemas are asserted in tests.
- [ ] If I added new DB indices, I checked, that they are not redundant, with PGHero or other tools.
- [ ] If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved token full-text search so filtering works consistently for tokens with and without symbols.

* **Chores**
  * Added a background index operation to boost token-name FTS performance.
  * Centralized full-text search filtering into a reusable helper for more reliable and maintainable search behavior.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Comment by nikitosing** [comment]
> Please process CodeRabbit suggestions

@vbaranov Processed

File: apps/explorer/priv/repo/migrations/20251126144325_add_tokens_name_partial_fts_index.exs [hunk 1]
```diff
@@ -0,0 +1,13 @@
+defmodule Explorer.Repo.Migrations.AddTokensNamePartialFtsIndex do
+  use Ecto.Migration
+
+  def up do
+    execute("""
+    CREATE INDEX tokens_name_partial_fts_index ON tokens USING GIN (to_tsvector('english', name)) WHERE symbol IS NULL
```
Comment (vbaranov) [inline apps/explorer/priv/repo/migrations/20251126144325_add_tokens_name_partial_fts_index.exs]: Foreground migrations on the `tokens` table in the latest release caused significant downtime on some huge explorer instances. Let's re-work it to background migration approach.

Comment (nikitosing) [reply apps/explorer/priv/repo/migrations/20251126144325_add_tokens_name_partial_fts_index.exs]: Done!

**Review by vbaranov — APPROVED** [review]
