### PR TITLE
fix: Fix log decoding bug

### LINKED ISSUE #11267: Logs have wrong decoded values
On the address page log has wrong amount
Image
Image
https://blockscout.lisk.com/api/v2/transactions/0xdaf1df46a71505d28980bce53547caaeb113df6cff196053fb1e1cc6c4e1a80e/logs

### PR DESCRIPTION
**Pull request by nikitosing**
Closes #11267 

## Changelog
- store in events_acc not results, but candidates from DB

## Checklist for your Pull Request (PR)

- [ ] If I added new functionality, I added tests covering it.
- [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
- [ ] I checked whether I should update the docs and did so by submitting a PR to [docs repository](https://github.com/blockscout/docs).
- [ ] If I added/changed/removed ENV var, I submitted a PR to [docs repository](https://github.com/blockscout/docs) to update the list of [env vars](https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md) and I updated the version to `master` in the Version column. If I removed variable, I added it to [Deprecated ENV Variables](https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables/deprecated-env-variables/README.md) page. After merging docs PR, changes will be reflected in these [pages](https://docs.blockscout.com/for-developers/information-and-settings/env-variables).
- [ ] If I added new DB indices, I checked, that they are not redundant, with PGHero or other tools.
- [ ] If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

### CODE REVIEW

**Review by sl1depengwyn — APPROVED** [review]

File: apps/explorer/lib/explorer/chain/log.ex [hunk 1]
```diff
@@ -233,28 +233,34 @@ defmodule Explorer.Chain.Log do
...
   end
 
-  defp find_method_candidates(log, transaction, options, events_acc, skip_sig_provider?) do
+  defp find_method_candidates(log, transaction, options, events_acc) do
     if is_nil(log.first_topic) do
       {{:error, :could_not_decode}, events_acc}
     else
       <<method_id::binary-size(4), _rest::binary>> = log.first_topic.bytes
-      key = {method_id, log.second_topic, log.third_topic, log.fourth_topic}
+      key = method_id
```
Comment (vbaranov) [inline apps/explorer/lib/explorer/chain/log.ex:241]: It seems like a redundant assignment after sticking to a single var as a key. We can omit it.
