### PR TITLE
Fix sourcify bug

### LINKED ISSUE #4387: Error opening contract page on the instance for the chain which is not supported by Sourcify
This instance doesn't have any `..._SOURCIFY_...` env variables provided.

```
blockscout-core    | Request: GET /address/0x2072699Fe4E3Ab5F20a0b16CaA5dfF9303443358/contracts
blockscout-core    | ** (exit) an exception was raised:
blockscout-core    |     ** (ArgumentError) argument error
blockscout-core    |         :erlang.bit_size(nil)
blockscout-core    |         (explorer 0.0.1) lib/explorer/third_party_integrations/sourcify.ex:210: Explorer.ThirdPartyIntegrations.Sourcify.get_metadata_any_url/0
blockscout-core    |         (explorer 0.0.1) lib/explorer/third_party_integrations/sourcify.ex:17: Explorer.ThirdPartyIntegrations.Sourcify.check_by_address_any/1
blockscout-core    |         (block_scout_web 0.0.1) lib/block_scout_web/controllers/address_contract_verification_controller.ex:287: BlockScoutWeb.AddressContractVerificationController.check_and_verify/1
blockscout-core    |         (block_scout_web 0.0.1) lib/block_scout_web/controllers/address_contract_controller.ex:24: BlockScoutWeb.AddressContractController.index/2
blockscout-core    |         (block_scout_web 0.0.1) lib/block_scout_web/controllers/address_contract_controller.ex:2: BlockScoutWeb.AddressContractController.action/2
blockscout-core    |         (block_scout_web 0.0.1) lib/block_scout_web/controllers/address_contract_controller.ex:2: BlockScoutWeb.AddressContractController.phoenix_controller_pipeline/2
blockscout-core    |         (phoenix 1.5.6) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
```

### PR DESCRIPTION
**Pull request by nikitosing**
Close #4387 

### Bug Fixes
- Added check if sourcify integration is enabled in `BlockScoutWeb.AddressContractVerificationController.check_and_verify/1`

## Checklist for your Pull Request (PR)

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

### CODE REVIEW

File: apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_controller.ex [hunk 1]
```diff
@@ -272,27 +272,29 @@ defmodule BlockScoutWeb.AddressContractVerificationController do
...
-      if Chain.smart_contract_verified?(address_hash_string) do
-        case Sourcify.check_by_address(address_hash_string) do
-          {:ok, _verified_status} ->
-            get_metadata_and_publish(address_hash_string, nil)
-
-          _ ->
-            {:error, :not_verified}
-        end
+    if Application.get_env(:explorer, Explorer.ThirdPartyIntegrations.Sourcify)[:enabled] do
+      if Chain.smart_contract_fully_verified?(address_hash_string) do
```
Comment (vbaranov) [inline apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_controller.ex:276]: Shouldn't this case work even without enabled integration with Sourcify?

**Review by vbaranov — COMMENTED** [review]
Left comment in the code

File: apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_controller.ex (hunk 1 above)
Comment (nikitosing) [reply apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_controller.ex]: fixed

**Review by vbaranov — APPROVED** [review]
