### PR TITLE
fix: Refactor TokenInstanceMetadataRefetch on demand fetcher

### LINKED ISSUE #12388: Single NFT metadata refetch doesn't account for `{id}` placeholder in metadata URL (ERC-1155)
## Description

Trying to refetch metadata via `/api/v2/tokens/{{collection}}/instances/{{token_id}}/refetch-metadata` for a token with `{id}` in metadata URL results in an error.

Example:
https://explorer.immutable.com/token/0x29c3A209d8423f9A53Bf8AD39bBb85087a2A938B/instance/103
`https://whatgamestudios.com/14numbers/nfts/{id}.json`

In this case correct metadata is stored at `https://whatgamestudios.com/14numbers/nfts/0000000000000000000000000000000000000000000000000000000000000067.json`, but the fetcher tries accessing the original string with `{id}.json`

## Version

[v8.0.2](https://github.com/blockscout/blockscout/tree/v8.0.2)

### PR DESCRIPTION
**Pull request by nikitosing**
Closes #12388 

## Changelog
- Make `TokenInstanceMetadataRefetch` use general functions from `Indexer.Fetcher.TokenInstance.Helper`
- Add new event: `not_fetched_token_instance_metadata`, payload:  `%{token_id: ^token_id, reason: "error"}`, reason either `error` or `retry_cooldown`

## Checklist for your Pull Request (PR)

- [ ] If I added new functionality, I added tests covering it.
- [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
- [ ] I checked whether I should update the docs and did so by submitting a PR to [docs repository](https://github.com/blockscout/docs).
- [ ] If I added/changed/removed ENV var, I submitted a PR to [docs repository](https://github.com/blockscout/docs) to update the list of [env vars](https://github.com/blockscout/docs/blob/master/setup/env-variables/README.md) and I updated the version to `master` in the Version column. If I removed variable, I added it to [Deprecated ENV Variables](https://github.com/blockscout/docs/blob/master/setup/env-variables/deprecated-env-variables/README.md) page. After merging docs PR, changes will be reflected in these [pages](https://docs.blockscout.com/setup/env-variables).
- [ ] If I added new DB indices, I checked, that they are not redundant, with PGHero or other tools.
- [ ] If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

## Summary by CodeRabbit

- **New Features**
  - Added real-time event and broadcast for failed token instance metadata fetches, enabling users to receive immediate feedback when metadata retrieval does not succeed.

- **Bug Fixes**
  - Improved handling and notification of token instance metadata fetch failures, ensuring accurate status updates.

- **Tests**
  - Added and updated tests to verify correct broadcasting and handling of failed token instance metadata fetch events.

- **Refactor**
  - Streamlined metadata fetching and event broadcasting logic for better maintainability and reliability.
  - Enhanced token metadata update process to include additional metadata-related flags and URLs.

### CODE REVIEW

**Review by sl1depengwyn — APPROVED** [review]

File: apps/indexer/lib/indexer/fetcher/on_demand/token_instance_metadata_refetch.ex [hunk 1]
```diff
@@ -39,60 +38,63 @@ defmodule Indexer.Fetcher.OnDemand.TokenInstanceMetadataRefetch do
...
+            fetched_token_instance_metadata: [
+              to_string(token_instance.token_contract_address_hash),
+              NFT.prepare_token_id(token_instance.token_id),
+              metadata
+            ]
+          },
+          :on_demand
+        )
+
+        Queue.process_new_instances([%TokenInstance{token_instance | metadata: metadata}])
```
Comment (vbaranov) [inline apps/indexer/lib/indexer/fetcher/on_demand/token_instance_metadata_refetch.ex:80]: Nitpick: define `token_contract_address_hash` and `token_id` right in the function arguments to replace long `token_instance.token_contract_address_hash` to `token_contract_address_hash` 
and
`token_instance.token_id` to `token_id`

```suggestion
  defp fetch_and_broadcast_metadata(
         %{token_id: token_id, token_contract_address_hash: token_contract_address_hash} = token_instance
       ) do
    case Helper.batch_prepare_instances_insert_params([
           %{contract_address_hash: token_contract_address_hash, token_id: token_id}
         ]) do
      [%{error: nil, metadata: metadata} = result] ->
        TokenInstance.set_metadata(token_instance, result)

        Publisher.broadcast(
          %{
            fetched_token_instance_metadata: [
              to_string(token_contract_address_hash),
              NFT.prepare_token_id(token_id),
              metadata
            ]
          },
          :on_demand
        )

        Queue.process_new_instances([%TokenInstance{token_instance | metadata: metadata}])
```

File: apps/indexer/lib/indexer/fetcher/on_demand/token_instance_metadata_refetch.ex [hunk 2]
```diff
@@ -39,60 +38,63 @@ defmodule Indexer.Fetcher.OnDemand.TokenInstanceMetadataRefetch do
...
+        Publisher.broadcast(
+          %{
+            not_fetched_token_instance_metadata: [
+              to_string(token_instance.token_contract_address_hash),
+              NFT.prepare_token_id(token_instance.token_id),
+              "error"
+            ]
+          },
+          :on_demand
+        )
```
Comment (vbaranov) [inline apps/indexer/lib/indexer/fetcher/on_demand/token_instance_metadata_refetch.ex:96]:
```suggestion
          "Error while refetching metadata for {#{token_contract_address_hash}, #{token_id}}: #{inspect(error)}"
        end)

        Publisher.broadcast(
          %{
            not_fetched_token_instance_metadata: [
              to_string(token_contract_address_hash),
              NFT.prepare_token_id(token_id),
              "error"
            ]
          },
          :on_demand
        )
```

**Review by vbaranov — APPROVED** [review]
