### PR TITLE
fix: Don't send logs without topic to sig provider

### LINKED ISSUE #12530: Don't send logs with no topic to sig provider

### PR DESCRIPTION
**Pull request by nikitosing**
Closes #12530 

## Changelog
-  Don't send logs without topic to sig provider
## Checklist for your Pull Request (PR)

- [ ] If I added new functionality, I added tests covering it.
- [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
- [ ] I checked whether I should update the docs and did so by submitting a PR to [docs repository](https://github.com/blockscout/docs).
- [ ] If I added/changed/removed ENV var, I submitted a PR to [docs repository](https://github.com/blockscout/docs) to update the list of [env vars](https://github.com/blockscout/docs/blob/master/setup/env-variables/README.md) and I updated the version to `master` in the Version column. If I removed variable, I added it to [Deprecated ENV Variables](https://github.com/blockscout/docs/blob/master/setup/env-variables/deprecated-env-variables/README.md) page. After merging docs PR, changes will be reflected in these [pages](https://docs.blockscout.com/setup/env-variables).
- [ ] If I added new DB indices, I checked, that they are not redundant, with PGHero or other tools.
- [ ] If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

## Summary by CodeRabbit

- **Bug Fixes**
  - Improved handling of logs without topics, ensuring they are ignored during decoding with the signature provider and preventing errors.
  - Updated URL encoding for batch event decoding requests to improve compatibility.

- **Tests**
  - Added a test to verify that logs without topics are ignored when decoding with the signature provider and that only relevant logs are sent for decoding.

### CODE REVIEW

File: apps/explorer/lib/explorer/smart_contract/sig_provider_interface.ex [hunk 1]
```diff
@@ -142,7 +142,7 @@ defmodule Explorer.SmartContract.SigProviderInterface do
 
   defp decode_event_url, do: "#{base_api_url()}" <> "/event"
 
-  defp decode_events_batch_url, do: "#{base_api_url()}" <> "/events:batch-get"
+  defp decode_events_batch_url, do: "#{base_api_url()}" <> "/events%3Abatch-get"
```
Comment (sl1depengwyn) [inline apps/explorer/lib/explorer/smart_contract/sig_provider_interface.ex:146]: I suggest not to add this to `cspell.json` but to ignore this particular case since `abatch` is not a valid word in general

**Review by sl1depengwyn — APPROVED** [review]

**Review by vbaranov — APPROVED** [review]
