### PR TITLE
Fix read contract and change tx count

### LINKED ISSUE #5518: Smart-contracts interaction, balanceOf method: no function clause matching in Integer.parse/2
```
Request: GET /smart-contracts/0x93d0c9a35c43f6BC999416A06aaDF21E68B29EBA?function_name=balanceOf&method_id=00fdd58e&args%5B%5D=0x343aa9b908bf6ef8d0e954221789881750c9c3ce&args%5B%5D=873
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Integer.parse/2
        (elixir 1.13.1) lib/integer.ex:275: Integer.parse(nil, 10)
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/smart_contract_controller.ex:110: BlockScoutWeb.SmartContractController.show/2
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/smart_contract_controller.ex:1: BlockScoutWeb.SmartContractController.action/2
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/smart_contract_controller.ex:1: BlockScoutWeb.SmartContractController.phoenix_controller_pipeline/2
        (phoenix 1.5.13) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (phoenix 1.5.13) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2
        (phoenix 1.5.13) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (block_scout_web 0.0.1) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint.plug_builder_call/2
```

### LINKED ISSUE #5738: Klin block explorer: 0 transactions counted, yet positive balance
See it for yourself: https://explorer.kiln.themerge.dev/address/0xA3c8eEA403F101cB288C3B31335240017f690505/transactions 

I see 65 ETH balance, yet the explorer says 0 transactions

### PR DESCRIPTION
**Pull request by nikitosing**
Close #5738 
Close #5518 

## Changelog
- Address txs count now counts all txs on address
- Fix backward compatibility issue with smart contract interaction

## Checklist for your Pull Request (PR)

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

### CODE REVIEW

File: apps/explorer/lib/explorer/chain.ex [hunk 1]
```diff
@@ -962,6 +962,17 @@ defmodule Explorer.Chain do
     Repo.aggregate(to_address_query, :count, :hash, timeout: :infinity)
   end
 
+  @spec address_hash_to_transaction_count(Hash.Address.t()) :: non_neg_integer()
+  def address_hash_to_transaction_count(address_hash) do
+    query =
+      from(
+        transaction in Transaction,
+        where: transaction.to_address_hash == ^address_hash or transaction.from_address_hash == ^address_hash
+      )
```
Comment (vbaranov) [inline apps/explorer/lib/explorer/chain.ex:971]: I suppose querying this if from DB every time will raise performance issues on this counter. I suggest organaizing ETS cache for this counter.

Comment (nikitosing) [reply apps/explorer/lib/explorer/chain.ex:971]: We already have it https://github.com/blockscout/blockscout/blob/master/apps/explorer/lib/explorer/counters/address_transactions_counter.ex

File: apps/explorer/lib/explorer/chain.ex [hunk 2]
```diff
@@ -962,6 +962,17 @@ defmodule Explorer.Chain do
     Repo.aggregate(to_address_query, :count, :hash, timeout: :infinity)
   end
 
+  @spec address_hash_to_transaction_count(Hash.Address.t()) :: non_neg_integer()
+  def address_hash_to_transaction_count(address_hash) do
```
Comment (vbaranov) [inline apps/explorer/lib/explorer/chain.ex:966]: The naming is incorrect. Since it accounts all transactions on address (to/from), I would suggest changing the naming of the function to `address_hash_all_transaction_count `

File: apps/explorer/lib/explorer/chain.ex [hunk 3]
```diff
@@ -2447,17 +2458,7 @@ defmodule Explorer.Chain do
 
   @spec address_to_transaction_count(Address.t()) :: non_neg_integer()
   def address_to_transaction_count(address) do
```
Comment (vbaranov) [inline apps/explorer/lib/explorer/chain.ex:2460]: It is worth changing the naming of the function since now it accounts all transactions on the address.

**Review by vbaranov — APPROVED** [review]

**Review by vbaranov — APPROVED** [review]
