### PR TITLE
fix: non-consensus logs in JSON RPC and ETH RPC APIs

### LINKED ISSUE #10498: Duplicate logs in API response due to `allow_non_consensus` flag
## Description

Logs from reorged blocks are returned in API response, resulting in identical duplicates (no block hash is returned). This leads to duplicates on the frontend as well, as the behaviour is the same in API v2.
[Client example for RPC API](https://rootstock-testnet.blockscout.com/api?module=logs&action=getLogs&address=0x00ca74491d9493bfe5451246c8c72849ba4a7f9d&toBlock=latest&fromBlock=5338249&topic0=0x7d84a6263ae0d98d3329bd7b46bb4e8d6f98cd35a7adb45c274c8b7fd5ebd5e0)

## Version

[v6.7.2-beta](https://github.com/blockscout/blockscout/tree/v6.7.2-beta)

### PR DESCRIPTION
**Pull request by k1rill-fedoseev**
Closes #10498 (cont. #10528)

### Bug Fixes

* Remove `allow_non_consensus` flag for JSON RPC `eth_getLogs` proxy, to be more compliant with the JSON RPC implementation in eth client.
* Treat "pending" in the same way as "latest" in the block range filters. Giving orphaned logs on "pending" filter is incorrect, it should either output logs from current to-be-mined block filled with mempool transactions (which blockscout does not currently index), or use "latest" instead of "pending" (a lot of public RPCs do that).
* Fix `block_consensus` filter by adding an extra filter on `log.block_hash == transaction.block_hash` in denormalized queries.

## Checklist for your Pull Request (PR)

- [ ] If I added new functionality, I added tests covering it.
- [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
- [ ] I checked whether I should update the docs and did so by submitting a PR to [docs repository](https://github.com/blockscout/docs).
- [ ] If I added/changed/removed ENV var, I submitted a PR to [docs repository](https://github.com/blockscout/docs) to update the list of [env vars](https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md) and I updated the version to `master` in the Version column. If I removed variable, I added it to [Deprecated ENV Variables](https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables/deprecated-env-variables/README.md) page. After merging docs PR, changes will be reflected in these [pages](https://docs.blockscout.com/for-developers/information-and-settings/env-variables).
- [ ] If I added new DB indices, I checked, that they are not redundant, with PGHero or other tools.
- [ ] If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

### CODE REVIEW

File: apps/explorer/lib/explorer/etherscan/logs.ex [hunk 1]
```diff
@@ -88,7 +88,8 @@ defmodule Explorer.Etherscan.Logs do
       all_transaction_logs_query =
         from(log in subquery(logs_query),
           join: transaction in Transaction,
-          on: log.transaction_hash == transaction.hash,
+          on: log.transaction_hash == transaction.hash and log.block_hash == transaction.block_hash,
```
Comment (k1rill-fedoseev) [inline apps/explorer/lib/explorer/etherscan/logs.ex:91]: Didn't observe changes in the EXPLAIN queries for an added `log.block_hash == transaction.block_hash` condition.

**Review by Qwerty5Uiop — APPROVED** [review]

**Review by vbaranov — APPROVED** [review]
