### PR TITLE
fix: coin balance history with internal tx changes

### LINKED ISSUE #12058: Coin balance history does not include internal transactions for recipient
### Description

https://blockscout.lisk.com/address/0x413bc872D9e424A5683643d3A75343dC85A4b8EA?tab=coin_balance_history 
If the transfer was made by internal transaction we do not display the address, for example transaction https://blockscout.lisk.com/tx/0x31b703877d9f2f66099199a1d986bcbd885d0e2bbb74dcbd34a2f1d5ca33fe05?tab=index
to wallet https://blockscout.lisk.com/address/0x413bc872D9e424A5683643d3A75343dC85A4b8EA?tab=coin_balance_history
We can still see the state change but we should display all transactions for recipient, both normal ones and internal.

Image

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

-

### Type of the chain

_No response_

### Link to the page

https://blockscout.lisk.com/

### Steps to reproduce

_No response_

### Backend version

v7.0.2

### Frontend version

_No response_

### Elixir & Erlang/OTP versions

-

### Operating system

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sl1depengwyn**
Fix #12058 

## Changelog

- refactor: move coin balance related functions to coin balance module from chain module
- In case when no transaction with corresponding balance change is found, try to find a suitable internal transaction

Issues appeared while working on this one:
https://github.com/blockscout/blockscout/issues/12652
https://github.com/blockscout/blockscout/issues/12653

## Checklist for your Pull Request (PR)

- [ ] If I added new functionality, I added tests covering it.
- [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
- [ ] I checked whether I should update the docs and did so by submitting a PR to [docs repository](https://github.com/blockscout/docs).
- [ ] If I added/changed/removed ENV var, I submitted a PR to [docs repository](https://github.com/blockscout/docs) to update the list of [env vars](https://github.com/blockscout/docs/blob/master/setup/env-variables/README.md) and I updated the version to `master` in the Version column. If I removed variable, I added it to [Deprecated ENV Variables](https://github.com/blockscout/docs/blob/master/setup/env-variables/deprecated-env-variables/README.md) page. After merging docs PR, changes will be reflected in these [pages](https://docs.blockscout.com/setup/env-variables).
- [ ] If I added new DB indices, I checked, that they are not redundant, with PGHero or other tools.
- [ ] If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

## Summary by CodeRabbit

- **New Features**
  - Enhanced coin balance functionality with improved querying, streaming, pagination, timestamp interpolation, and transaction association for blockchain addresses.

- **Bug Fixes**
  - Improved accuracy and reliability of coin balance history and retrieval.

- **Tests**
  - Added comprehensive tests for new coin balance features and updated existing tests to reflect changes in coin balance handling.

- **Refactor**
  - Streamlined and reorganized coin balance logic into a dedicated module for better maintainability and performance.

### CODE REVIEW

File: apps/explorer/lib/explorer/chain/address/coin_balance.ex [hunk 1]
```diff
@@ -42,9 +42,340 @@ defmodule Explorer.Chain.Address.CoinBalance do
...
+      |> page_coin_balances(paging_options)
+      |> Chain.select_repo(options).all()
+      |> preload_transactions(options)
+
+    if Enum.empty?(balances_raw) do
+      balances_raw
+    else
+      balances_raw_filtered =
+        balances_raw
+        |> Enum.filter(fn balance -> balance.value end)
```
Comment (nikitosing) [inline apps/explorer/lib/explorer/chain/address/coin_balance.ex:215]: Why do we need this filter, if in query we already have `not is_nil(cb.value)` condition?
And if we still need this, so, you should consider placing this filtering before `preload_transactions/2` call.

Comment (sl1depengwyn) [reply apps/explorer/lib/explorer/chain/address/coin_balance.ex:215]: I have no idea, the function was moved from `Explorer.Chain` as is. I think it's better to leave it as is and refactor in other PR, so changes are more easy to review
