### PR TITLE
Complete fix pending sanitizer

### LINKED ISSUE #4427: Pending transactions sanitizer cannot assign block hash to tx
```
** (Ecto.ChangeError) value `"0x8e2bef69f495145f4fe5c415c5f752802621d784aad44ab78515b89ef581920c"` for `Explorer.Chain.Transaction.block_hash` in `update` does not match type Explorer.Chain.Hash.Full
    (ecto 3.5.5) lib/ecto/repo/schema.ex:889: Ecto.Repo.Schema.dump_field!/6
    (ecto 3.5.5) lib/ecto/repo/schema.ex:898: anonymous fn/6 in Ecto.Repo.Schema.dump_fields!/5
    (stdlib 3.14.1) maps.erl:233: :maps.fold_1/3
    (ecto 3.5.5) lib/ecto/repo/schema.ex:896: Ecto.Repo.Schema.dump_fields!/5
    (ecto 3.5.5) lib/ecto/repo/schema.ex:829: Ecto.Repo.Schema.dump_changes!/6
    (ecto 3.5.5) lib/ecto/repo/schema.ex:334: anonymous fn/15 in Ecto.Repo.Schema.do_update/4
    (indexer 0.1.0) lib/indexer/pending_transactions_sanitizer.ex:168: Indexer.PendingTransactionsSanitizer.invalidate_block/4
    (elixir 1.11.4) lib/enum.ex:798: Enum."-each/2-lists^foreach/1-0-"/2
Last message: :sanitize_pending_transactions
```

The error began to appear after deployment of https://github.com/blockscout/blockscout/pull/4360

### PR DESCRIPTION
**Pull request by nikitosing**
Close #4427 

### Bug Fixes
- Fix PendingTransactionsSanitizer for non-consensus blocks

## Checklist for your Pull Request (PR)

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

### CODE REVIEW

File: apps/indexer/lib/indexer/pending_transactions_sanitizer.ex [hunk 1]
```diff
@@ -159,15 +161,25 @@ defmodule Indexer.PendingTransactionsSanitizer do
 
       Blocks.lose_consensus(Repo, [], [block_number], [], opts)
     else
+      {:ok, hash} = Hash.cast(block_hash)
+      tx_info = to_elixir(tx)
+
       changeset =
         pending_tx
         |> Transaction.changeset()
+        |> Changeset.put_change(:cumulative_gas_used, tx_info["gas"])
```
Comment (vbaranov) [inline apps/indexer/lib/indexer/pending_transactions_sanitizer.ex:170]: I think we should use `eth_getTransactionReceipt` RPC method call in order to properly fetch `gas_used` and `cumulative_gas_used `. Thus, I suggest to replace `eth_getTransactionByHash` with `eth_getTransactionReceipt` in pending transactions sanitizer.

**Review by vbaranov — CHANGES_REQUESTED** [review]

**Review by vbaranov — APPROVED** [review]
