### PR TITLE
fix: Add missing preloads

### LINKED ISSUE #8839: Contract verification status isn't displayed on 'Token transfers' tab
## Description

Backend returns `"is_verified": null` for a verified contract on 'Token transfers' tab

## Version

[v5.3.1-beta.+commit.bc1b1d16](https://github.com/blockscout/blockscout/commit/bc1b1d16)

## Links and screenshots

https://eth.blockscout.com/address/0x6Bba316c48b49BD1eAc44573c5c871ff02958469?tab=token_transfers

https://eth.blockscout.com/api/v2/addresses/0x6Bba316c48b49BD1eAc44573c5c871ff02958469/token-transfers?type=

Image

### LINKED ISSUE #9402: Add smart-contract preload
- [ ] Add smart contracts preload in order to send implementation name and smart contract verification status via API
- [ ] Add smart contracts preload to the transactions which are emitted via websocket

### PR DESCRIPTION
**Pull request by nikitosing**
Closes #9402 
Closes #8839 

## Changelog
- Add missing preloads
- Refactor `flat_1155_batch_token_transfers/2`

## Checklist for your Pull Request (PR)

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

### CODE REVIEW

File: apps/explorer/lib/explorer/chain.ex [hunk 1]
```diff
@@ -5033,23 +5033,25 @@ defmodule Explorer.Chain do
...
           transfers = flat_1155_batch_token_transfer(tt, tt.amounts, token_ids, token_id)
 
-          acc ++ transfers
+          transfers ++ acc
 
         _ ->
-          Enum.reverse([tt | Enum.reverse(acc)])
+          [tt | acc]
       end
     end)
```
Comment (sl1depengwyn) [inline apps/explorer/lib/explorer/chain.ex:5053]: Maybe we can reduce this to two clauses, like
```elixir
      case tt.token_ids do
        [_, _ | _] = token_ids ->
          transfers = flat_1155_batch_token_transfer(tt, tt.amounts, token_ids, token_id)

          transfers ++ acc

        _ ->
          [tt | acc]
      end
    end
  end
```

Comment (nikitosing) [reply apps/explorer/lib/explorer/chain.ex]: good suggestion processed in 5b4cf7dde90adf6aded7c6e51d3afef6a885f843

**Review by sl1depengwyn — APPROVED** [review]

**Review by vbaranov — APPROVED** [review]
