### PR TITLE
Fix polygon tracer

### LINKED ISSUE #8241: Polygon Edge: failed to fetch internal transactions for blocks: ** (ArithmeticError) bad argument in arithmetic expression
```
blockscout               | 2023-08-18T07:34:22.437 application=indexer fetcher=internal_transaction count=5 error_count=5 [error] failed to fetch internal transactions for blocks: ** (ArithmeticError) bad argument in arithmetic expression
blockscout               |     :erlang.*(nil, 2)
blockscout               |     (ethereum_jsonrpc 5.2.1) lib/ethereum_jsonrpc/geth/polygon_tracer.ex:308: EthereumJSONRPC.Geth.PolygonTracer.call_op/3
blockscout               |     (elixir 1.14.5) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
blockscout               |     (ethereum_jsonrpc 5.2.1) lib/ethereum_jsonrpc/geth/polygon_tracer.ex:52: EthereumJSONRPC.Geth.PolygonTracer.replay/3
blockscout               |     (ethereum_jsonrpc 5.2.1) lib/ethereum_jsonrpc/geth.ex:148: anonymous fn/5 in EthereumJSONRPC.Geth.debug_trace_transaction_responses_to_internal_transactions_params/3
blockscout               |     (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
blockscout               |     (ethereum_jsonrpc 5.2.1) lib/ethereum_jsonrpc/geth.ex:146: EthereumJSONRPC.Geth.debug_trace_transaction_responses_to_internal_transactions_params/3
blockscout               |     (indexer 5.2.1) lib/indexer/fetcher/internal_transaction.ex:206: anonymous fn/3 in Indexer.Fetcher.InternalTransaction.fetch_block_internal_transactions_by_transactions/2
```

### LINKED ISSUE #8485: Polygon tracing: take into account address from stack in CALLs
Based on this PR https://github.com/0xPolygon/polygon-edge/pull/1654

### PR DESCRIPTION
**Pull request by sl1depengwyn**
Close #8485
Fix #8241  

## Changelog

- Add fallback to 0 in case of `nil` `input_length`
- Add handling of additional fields in stack

## Checklist for your Pull Request (PR)

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

### CODE REVIEW

File: apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth/polygon_tracer.ex [hunk 1]
```diff
@@ -287,7 +287,7 @@ defmodule EthereumJSONRPC.Geth.PolygonTracer do
            calls: calls
          } = ctx
        ) do
-    log_stack = Enum.reverse(log_stack)
+    [_, to | log_stack] = Enum.reverse(log_stack)
```
Comment (vbaranov) [inline apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth/polygon_tracer.ex:290]: Is it possible, that log_stack can contain 1 element? Then, tracing will fail on this line.
Are we ok, that we extract last two elements from the initial log_stack object (this is different from the previous implementation) and then use this stripped down object later?

Comment (sl1depengwyn) [reply apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth/polygon_tracer.ex:290]: Case, when `log_stack` contains less than 3 elements handled by previous clause.
Logic is similar to geth tracer https://github.com/blockscout/blockscout/blob/a4ead7a54e1f3e67d6e39fc19e7e94840c0bb83f/apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth/tracer.ex#L255
