### PR TITLE
Do not preload smart contract info if address has no contract_code

### LINKED ISSUE #8730: API v2: EOA address page low performance
### Description

```
1> address_options = [
1>     necessity_by_association: %{
1>       :contracts_creation_internal_transaction => :optional,
1>       :names => :optional,
1>       :smart_contract => :optional,
1>       :token => :optional,
1>       :contracts_creation_transaction => :optional
1>     },
1>     api?: true
1>   ]
[
  necessity_by_association: %{
    contracts_creation_internal_transaction: :optional,
    contracts_creation_transaction: :optional,
    names: :optional,
    smart_contract: :optional,
    token: :optional
  },
  api?: true
]
2> address_hash_string = "0x0000000000000000000000000000000000000000"
"0x0000000000000000000000000000000000000000"
3> {:ok, address_hash} = Explorer.Chain.string_to_address_hash(address_hash_string)
{:ok,
 %Explorer.Chain.Hash{
   byte_count: 20,
   bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>
 }}
4> {:ok, address} = Explorer.Chain.hash_to_address(address_hash, address_options)

10:25:14.785 [debug] QUERY OK source="addresses" db=7.9ms idle=1422.6ms
SELECT a0."hash", a0."fetched_coin_balance", a0."fetched_coin_balance_block_number", a0."contract_code", a0."nonce", a0."decompiled", a0."verified", a0."transactions_count", a0."token_transfers_count", a0."gas_used", a0."inserted_at", a0."updated_at", s1."has_decompiled_code?" FROM "addresses" AS a0 LEFT OUTER JOIN (SELECT sd0."address_hash" AS "address_hash", NOT (sd0."address_hash" IS NULL) AS "has_decompiled_code?" FROM "decompiled_smart_contracts" AS sd0 WHERE (sd0."address_hash" = $1) LIMIT 1) AS s1 ON a0."hash" = s1."address_hash" WHERE (a0."hash" = $2) [%Explorer.Chain.Hash{byte_count: 20, bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>}, %Explorer.Chain.Hash{byte_count: 20, bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>}]

10:25:14.792 [debug] QUERY OK source="internal_transactions" db=7.3ms idle=325.3ms
SELECT i0."call_type", i0."created_contract_code", i0."error", i0."gas", i0."gas_used", i0."index", i0."init", i0."input", i0."output", i0."trace_address", i0."type", i0."value", i0."block_number", i0."transaction_index", i0."block_index", i0."inserted_at", i0."updated_at", i0."created_contract_address_hash", i0."from_address_hash", i0."to_address_hash", i0."transaction_hash", i0."block_hash", i0."created_contract_address_hash" FROM "internal_transactions" AS i0 WHERE (i0."created_contract_address_hash" = $1) [%Explorer.Chain.Hash{byte_count: 20, bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>}]

10:25:14.793 [debug] QUERY OK source="tokens" db=7.6ms idle=915.3ms
SELECT t0."name", t0."symbol", t0."total_supply", t0."decimals", t0."type", t0."cataloged", t0."holder_count", t0."skip_metadata", t0."total_supply_updated_at_block", t0."fiat_value", t0."circulating_market_cap", t0."icon_url", t0."is_verified_via_admin_panel", t0."contract_address_hash", t0."inserted_at", t0."updated_at", t0."contract_address_hash" FROM "tokens" AS t0 WHERE (t0."contract_address_hash" = $1) [%Explorer.Chain.Hash{byte_count: 20, bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>}]

10:25:14.793 [debug] QUERY OK source="address_names" db=7.6ms idle=915.3ms
SELECT a0."id", a0."name", a0."primary", a0."metadata", a0."address_hash", a0."inserted_at", a0."updated_at", a0."address_hash" FROM "address_names" AS a0 WHERE (a0."address_hash" = $1) ORDER BY a0."address_hash" [%Explorer.Chain.Hash{byte_count: 20, bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>}]

10:25:14.793 [debug] QUERY OK source="smart_contracts" db=7.6ms idle=915.3ms
SELECT s0."id", s0."name", s0."compiler_version", s0."optimization", s0."contract_source_code", s0."constructor_arguments", s0."evm_version", s0."optimization_runs", s0."external_libraries", s0."abi", s0."verified_via_sourcify", s0."partially_verified", s0."file_path", s0."is_vyper_contract", s0."is_changed_bytecode", s0."bytecode_checked_at", s0."contract_code_md5", s0."implementation_name", s0."compiler_settings", s0."implementation_fetched_at", s0."implementation_address_hash", s0."verified_via_eth_bytecode_db", s0."address_hash", s0."inserted_at", s0."updated_at", s0."address_hash" FROM "smart_contracts" AS s0 WHERE (s0."address_hash" = $1) [%Explorer.Chain.Hash{byte_count: 20, bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>}]

10:26:14.787 [debug] QUERY ERROR source="transactions" db=60001.5ms idle=915.4ms
SELECT t0."hash", t0."block_number", t0."cumulative_gas_used", t0."earliest_processing_start", t0."error", t0."gas", t0."gas_price", t0."gas_used", t0."index", t0."created_contract_code_indexed_at", t0."input", t0."nonce", t0."r", t0."s", t0."status", t0."v", t0."value", t0."revert_reason", t0."max_priority_fee_per_gas", t0."max_fee_per_gas", t0."type", t0."has_error_in_internal_txs", t0."old_block_hash", t0."inserted_at", t0."updated_at", t0."block_hash", t0."from_address_hash", t0."to_address_hash", t0."created_contract_address_hash", t0."created_contract_address_hash" FROM "transactions" AS t0 WHERE (t0."created_contract_address_hash" = $1) [%Explorer.Chain.Hash{byte_count: 20, bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>}]
** (EXIT from #PID<0.23483.17>) shell process exited with reason: an exception was raised:
    ** (DBConnection.ConnectionError) ssl recv: closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)
        (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1047: Ecto.Adapters.SQL.raise_sql_call_error/1
        (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:945: Ecto.Adapters.SQL.execute/6
        (ecto 3.10.3) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
        (ecto 3.10.3) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
        (ecto 3.10.3) lib/ecto/repo/preloader.ex:272: Ecto.Repo.Preloader.fetch_query/8
        (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
        (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4
        (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

Query of such type:
```
SELECT t0."hash", t0."block_number", t0."cumulative_gas_used", t0."earliest_processing_start", t0."error", t0."gas", t0."gas_price", t0."gas_used", t0."index", t0."created_contract_code_indexed_at", t0."input", t0."nonce", t0."r", t0."s", t0."status", t0."v", t0."value", t0."revert_reason", t0."max_priority_fee_per_gas", t0."max_fee_per_gas", t0."type", t0."has_error_in_internal_txs", t0."old_block_hash", t0."inserted_at", t0."updated_at", t0."block_hash", t0."from_address_hash", t0."to_address_hash", t0."created_contract_address_hash", t0."created_contract_address_hash" FROM "transactions" AS t0 WHERE (t0."created_contract_address_hash" = '\x0000000000000000000000000000000000000000')
```
can be very slow for EOA (tens of seconds or even minutes). And it will block the response of the endpoint for EOA.

However, we can know in advance if the address is contract or not by checking presense of `contract_code` in `addresses` table (quite cheap query). And thus if we detected, that the address is EOA rather than contract, we shouldn't add:
```
:contracts_creation_internal_transaction => :optional,
:contracts_creation_transaction => :optional
```
preloads for it. Thus, it will eliminate 2 potentially heavy queries for EOAs.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Any

### Type of the chain

_No response_

### Link to the page

_No response_

### Steps to reproduce

_No response_

### Backend version

v5.3.1

### Frontend version

_No response_

### Elixir & Erlang/OTP versions

Elixir 1.14.5

### Operating system

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by nikitosing**
Close #8730 

## Changelog
- Do not preload smart contract info if address has no contract_code

## Checklist for your Pull Request (PR)

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

### CODE REVIEW

File: apps/block_scout_web/lib/block_scout_web/controllers/api/v2/address_controller.ex [hunk 1]
```diff
@@ -477,4 +482,9 @@ defmodule BlockScoutWeb.API.V2.AddressController do
       {:ok, address_hash, address}
     end
   end
+
+  defp maybe_preload_smart_contract_associations(%Address{contract_code: nil} = address), do: address
+
+  defp maybe_preload_smart_contract_associations(%Address{contract_code: _} = address),
+    do: Repo.replica().preload(address, @contract_address_preloads)
```
Comment (sl1depengwyn) [inline apps/block_scout_web/lib/block_scout_web/controllers/api/v2/address_controller.ex:489]: Please, move this logic to Explorer module

**Review by vbaranov — APPROVED** [review]
