### PR TITLE
fix: atoms in token_transfers_next_page_params

### LINKED ISSUE #12989: Write regress tests for prosessing non-atoms in next_page_params
Related changes to fix the bug are in https://github.com/blockscout/blockscout/pull/12986.

### PR DESCRIPTION
**Pull request by sl1depengwyn**
Close #12989
## Checklist for your Pull Request (PR)

- [ ] If I added new functionality, I added tests covering it.
- [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
- [ ] I checked whether I should update the docs and did so by submitting a PR to [docs repository](https://github.com/blockscout/docs).
- [ ] If I added/changed/removed ENV var, I submitted a PR to [docs repository](https://github.com/blockscout/docs) to update the list of [env vars](https://github.com/blockscout/docs/blob/master/setup/env-variables/README.md) and I updated the version to `master` in the Version column. If I removed variable, I added it to [Deprecated ENV Variables](https://github.com/blockscout/docs/blob/master/setup/env-variables/deprecated-env-variables/README.md) page. After merging docs PR, changes will be reflected in these [pages](https://docs.blockscout.com/setup/env-variables).
- [ ] If I added new DB indices, I checked, that they are not redundant, with PGHero or other tools.
- [ ] If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

## Summary by CodeRabbit

- **Bug Fixes**
  - Fixed pagination parameter handling to avoid duplicate/conflicting keys and standardized key representations, ensuring stable next-page links and consistent navigation.
  - Improved token transfer pagination (including batched transfers) so next-page links, batch fields and item counts remain accurate and reliable.

- **Tests**
  - Added tests covering pagination helpers and batched token-transfer scenarios to prevent regressions and verify deduplication behavior.

### CODE REVIEW

File: apps/block_scout_web/lib/block_scout_web/chain.ex [hunk 1]
```diff
@@ -989,7 +998,17 @@ defmodule BlockScoutWeb.Chain do
         index_in_batch: current_token_transfer.index_in_batch
       })
     else
-      Map.merge(params, paging_params(List.last(list)))
+      new_params = paging_params(List.last(list))
```
Comment (nikitosing) [inline apps/block_scout_web/lib/block_scout_web/chain.ex:989]: Shouldn't we also drop `["batch_log_index", "batch_block_hash", "batch_transaction_hash", "index_in_batch"]` in this branch?

Comment (sl1depengwyn) [reply apps/block_scout_web/lib/block_scout_web/chain.ex:989]: Done

File: apps/block_scout_web/lib/block_scout_web/chain.ex [hunk 2]
```diff
@@ -989,7 +998,21 @@ defmodule BlockScoutWeb.Chain do
...
+
+      atomized_keys =
+        new_params
+        |> Map.keys()
+        |> Enum.map(fn
+          key when is_atom(key) -> Atom.to_string(key)
+          key -> key
+        end)
```
Comment (nikitosing) [inline apps/block_scout_web/lib/block_scout_web/chain.ex]: Let's wrap it to a function. It's already used 3 times.

Comment (sl1depengwyn) [reply apps/block_scout_web/lib/block_scout_web/chain.ex]: Done

**Review by nikitosing — APPROVED** [review]

**Review by ajit2903 — COMMENTED** [review]
Add
