### PR TITLE
fix: Fix Unknown UID bug at smart-contract verification

### LINKED ISSUE #9985: Unknown UID error on async API v1 verification

### PR DESCRIPTION
**Pull request by nikitosing**
Closes #9985 

## Changelog
- Add fallback fetching UID status from Que

## Checklist for your Pull Request (PR)

  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I added new DB indices, I checked, that they are not redundant with PGHero or other tools.
  - [ ] If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

### CODE REVIEW

File: apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex [hunk 1]
```diff
@@ -219,10 +220,29 @@ defmodule BlockScoutWeb.API.RPC.ContractController do
         render(conn, :show, %{result: "Fail - Unable to verify"})
 
       :unknown_uid ->
-        render(conn, :show, %{result: "Unknown UID"})
+        if find_uid_in_queue(guid) do
+          render(conn, :show, %{result: "Pending in queue"})
+        else
+          render(conn, :show, %{result: "Unknown UID"})
+        end
```
Comment (vbaranov) [inline apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex:227]: Probably we could move this logic to fetch_status/1 function, that it doesn't return :unknown_id, if the id is found in the queue? And also we have similar function for `checkproxyverification` endpoint? Should we extrapolate this logic there too?

Comment (nikitosing) [reply apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex]: Makes sense, fixed in 3260de73fd8b2d80707064395dc12f584aa42111
For `checkproxyverification` it's not required, since we do synchronous insert

Comment (vbaranov) [reply apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex]: What about
> And also we have similar function for checkproxyverification endpoint? Should we extrapolate this logic there too?

?

`checkproxyverification` endpoint uses `Explorer.Chain.SmartContract.Proxy.VerificationStatus.fetch_status/1`, which stayed untouched.

Comment (nikitosing) [reply apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex]: We insert status before replying to the client https://github.com/blockscout/blockscout/blob/52dff5abc7e0c3b79638c50fc33894fe4a7b72ed/apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex#L237

Comment (vbaranov) [reply apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex]: Ah, I missed the 2nd part of your initial answer. Got it. Thanks.
