### PR TITLE
fix: sanitize addresses of smart contracts having `verified` set to `false` 

### LINKED ISSUE #11725: Missing `verified=true` in `addresses` table
Addresses corresponding to smart contracts verified via ETH Bytecode DB are missing `verified` flag set to `true`.

The following queries should return equal results:

Image

Image

### PR DESCRIPTION
**Pull request by fedor-ivn**
Closes #11725.

Adds a continuously running migration (runs on every   that sets `verified` field for entries from `addresses` table that have a corresponding entry in the `smart_contracts` table. Also does some refactoring around smart contract publisher modules.

P.S: related PR in docs repo: https://github.com/blockscout/docs/pull/375

## Checklist for your Pull Request (PR)

- [ ] If I added new functionality, I added tests covering it.
- [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
- [ ] I checked whether I should update the docs and did so by submitting a PR to [docs repository](https://github.com/blockscout/docs).
- [x] If I added/changed/removed ENV var, I submitted a PR to [docs repository](https://github.com/blockscout/docs) to update the list of [env vars](https://github.com/blockscout/docs/blob/master/setup/env-variables/README.md) and I updated the version to `master` in the Version column. If I removed variable, I added it to [Deprecated ENV Variables](https://github.com/blockscout/docs/blob/master/setup/env-variables/deprecated-env-variables/README.md) page. After merging docs PR, changes will be reflected in these [pages](https://docs.blockscout.com/setup/env-variables).
- [ ] If I added new DB indices, I checked, that they are not redundant, with PGHero or other tools.
- [ ] If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

## Summary by CodeRabbit

- **New Features**
	- Introduced a new module for managing address verification migrations.
	- Added configuration options to enable or disable address verification features.
	- Added a new function for creating or updating smart contracts based on verification status.
	- Enhanced configuration for managing batch size and concurrency during address verification migrations.
	- Expanded in-memory cache to track the completion status of address verification migrations.

- **Refactor**
	- Centralized smart contract management logic in the main SmartContract module.
	- Streamlined the smart contract publishing process across different contract types (Solidity, Stylus, Vyper).
	- Updated module aliases to enhance contract handling.
	- Removed redundant contract-specific creation and update methods.
	- Enhanced process management for address verification during application startup.

### CODE REVIEW

File: apps/explorer/lib/explorer/migrator/sanitize_verified_addresses.ex [hunk 1]
```diff
@@ -0,0 +1,143 @@
...
+  end
+
+  defp batch_size do
+    Application.get_env(:explorer, __MODULE__)[:batch_size] || @default_batch_size
+  end
+
+  defp concurrency do
+    default = 4 * System.schedulers_online()
+
+    Application.get_env(:explorer, __MODULE__)[:concurrency] || default
```
Comment (vbaranov) [inline apps/explorer/lib/explorer/migrator/sanitize_verified_addresses.ex:141]: I'd suggest defining variables to manage batch size and concurrency of this migration in runtime as we do for other background migrations.

Comment (fedor-ivn) [reply apps/explorer/lib/explorer/migrator/sanitize_verified_addresses.ex:141]: Alright, agreed. Processed in 5b82fccda2fa4e835a12bd4301f69f02b8ce4c7b.  

By the way, should we introduce a `SANITIZE_VERIFIED_ADDRESSES_MIGRATION_ENABLED` env? Or should we force this migration to run anyway? If we do add the flag, what should its default value be — true or false? What do you think?

File: apps/explorer/lib/explorer/chain/cache/background_migrations.ex [hunk 2]
```diff
@@ -29,7 +29,8 @@ defmodule Explorer.Chain.Cache.BackgroundMigrations do
     key: :tt_denormalization_finished,
     key: :sanitize_duplicated_log_index_logs_finished,
     key: :backfill_multichain_search_db_finished,
-    key: :arbitrum_da_records_normalization_finished
+    key: :arbitrum_da_records_normalization_finished,
+    key: :sanitize_verified_addresses_finished
```
[the remark this answers is not in the document]
Comment (fedor-ivn) [reply apps/explorer/lib/explorer/chain/cache/background_migrations.ex:33]: Thanks, processed.

File: apps/explorer/lib/explorer/migrator/sanitize_verified_addresses.ex (hunk 1 above)
Comment (nikitosing) [reply apps/explorer/lib/explorer/migrator/sanitize_verified_addresses.ex:149]: I propose to introduce `MIGRATION_SANITIZE_VERIFIED_ADDRESSES_DISABLED` with default `false`

File: config/runtime.exs [hunk 3]
```diff
@@ -681,6 +681,10 @@ config :explorer, Explorer.Migrator.ArbitrumDaRecordsNormalization,
   batch_size: ConfigHelper.parse_integer_env_var("ARBITRUM_DA_RECORDS_NORMALIZATION_MIGRATION_BATCH_SIZE", 500),
   concurrency: ConfigHelper.parse_integer_env_var("ARBITRUM_DA_RECORDS_NORMALIZATION_MIGRATION_CONCURRENCY", 1)
 
+config :explorer, Explorer.Migrator.SanitizeVerifiedAddresses,
+  batch_size: ConfigHelper.parse_integer_env_var("SANITIZE_VERIFIED_ADDRESSES_MIGRATION_BATCH_SIZE", 500),
+  concurrency: ConfigHelper.parse_integer_env_var("SANITIZE_VERIFIED_ADDRESSES_MIGRATION_CONCURRENCY", 1)
```
Comment (nikitosing) [inline config/runtime.exs:686]: Lets rename it in order to come closer to consistency, and use common prefix `MIGRATION`
```suggestion
  batch_size: ConfigHelper.parse_integer_env_var("MIGRATION_SANITIZE_VERIFIED_ADDRESSES_BATCH_SIZE", 500),
  concurrency: ConfigHelper.parse_integer_env_var("MIGRATION_SANITIZE_VERIFIED_ADDRESSES_CONCURRENCY", 1)
```

File: apps/explorer/lib/explorer/migrator/sanitize_verified_addresses.ex [hunk 4]
```diff
@@ -0,0 +1,151 @@
...
```
[the remark this answers is not in the document]
Comment (fedor-ivn) [reply apps/explorer/lib/explorer/migrator/sanitize_verified_addresses.ex]: fixed in https://github.com/blockscout/blockscout/pull/11727/commits/adb7b5e461fc6daea76b60fa80ed8b83c4dcfdcd

File: config/runtime.exs (hunk 3 above)
Comment (fedor-ivn) [reply config/runtime.exs]: Thanks! Fixed in https://github.com/blockscout/blockscout/pull/11727/commits/adb7b5e461fc6daea76b60fa80ed8b83c4dcfdcd

File: apps/explorer/lib/explorer/migrator/sanitize_verified_addresses.ex (hunk 4 above)
[the remark this answers is not in the document]
Comment (fedor-ivn) [reply apps/explorer/lib/explorer/migrator/sanitize_verified_addresses.ex]: Also updated the corresponding PR in [docs](https://github.com/blockscout/docs/pull/375)

File: apps/explorer/lib/explorer/migrator/sanitize_verified_addresses.ex [hunk 5]
```diff
@@ -0,0 +1,156 @@
...
+
+  def unprocessed_data_query do
+    from(address in Address,
+      join: smart_contract in SmartContract,
+      on: address.hash == smart_contract.address_hash,
+      where: address.verified == false
+    )
+  end
+
+  def last_unprocessed_identifiers(state) do
```
Comment (nikitosing) [inline apps/explorer/lib/explorer/migrator/sanitize_verified_addresses.ex:26]: _Nitpick:_ As I see, `state` var is unused in this function, can we omit it then?

File: apps/explorer/lib/explorer/migrator/sanitize_verified_addresses.ex [hunk 6]
```diff
@@ -0,0 +1,156 @@
...
+  #
+  # ## Returns
+  # - Reference to the scheduled timer
+  @spec schedule_batch_migration(timeout :: non_neg_integer | nil) :: reference()
+  defp schedule_batch_migration(timeout \\ nil) do
+    Process.send_after(
+      self(),
+      :migrate_batch,
+      timeout ||
+        Application.get_env(:explorer, __MODULE__)[:timeout] ||
```
Comment (nikitosing) [inline apps/explorer/lib/explorer/migrator/sanitize_verified_addresses.ex:137]: I don't see such env in `runtime.ex`, shouldn't it be added in `runtime.ex`/deleted here?

File: apps/explorer/lib/explorer/migrator/sanitize_verified_addresses.ex [hunk 7]
```diff
@@ -0,0 +1,156 @@
...
+
+  alias Explorer.Chain.{Address, SmartContract}
+  alias Explorer.Chain.Cache.BackgroundMigrations
+  alias Explorer.Repo
+
+  def unprocessed_data_query do
+    from(address in Address,
+      join: smart_contract in SmartContract,
+      on: address.hash == smart_contract.address_hash,
+      where: address.verified == false
```
Comment (nikitosing) [inline apps/explorer/lib/explorer/migrator/sanitize_verified_addresses.ex:22]: column `verified` has no `NOT NULL` constraint, wdyt about addition `is_nil()` condition here?

File: apps/explorer/lib/explorer/smart_contract/stylus/publisher.ex [hunk 8]
```diff
@@ -144,22 +144,8 @@ defmodule Explorer.SmartContract.Stylus.Publisher do
...
-          {:error, Ecto.Changeset.t() | String.t()} | {:ok, Explorer.Chain.SmartContract.t()}
-  defp create_or_update_smart_contract(address_hash, attrs) do
     Logger.info("Publish successfully verified Stylus smart-contract #{address_hash} into the DB")
-
-    if SmartContract.verified?(address_hash) do
-      SmartContract.update_smart_contract(attrs, attrs.external_libraries, attrs.secondary_sources)
-    else
-      SmartContract.create_smart_contract(attrs, attrs.external_libraries, attrs.secondary_sources)
-    end
+    SmartContract.create_or_update_smart_contract(address_hash, attrs, false)
```
Comment (fedor-ivn) [inline apps/explorer/lib/explorer/smart_contract/stylus/publisher.ex:148]: @nikitosing Is it valid?

File: apps/explorer/lib/explorer/migrator/sanitize_verified_addresses.ex (hunk 6 above)
Comment (fedor-ivn) [reply apps/explorer/lib/explorer/migrator/sanitize_verified_addresses.ex:134]: You're right. Would it be useful to configure timeout in this migration, wdyt?

File: apps/explorer/lib/explorer/migrator/sanitize_verified_addresses.ex (hunk 7 above)
Comment (fedor-ivn) [reply apps/explorer/lib/explorer/migrator/sanitize_verified_addresses.ex]: Very good catch. We definitely need to add `is_nil` cond here. Fixed in e21d8bb3cf

File: apps/explorer/lib/explorer/migrator/sanitize_verified_addresses.ex (hunk 5 above)
Comment (fedor-ivn) [reply apps/explorer/lib/explorer/migrator/sanitize_verified_addresses.ex]: Thanks! Processed

File: apps/explorer/lib/explorer/migrator/sanitize_verified_addresses.ex (hunk 6 above)
Comment (nikitosing) [reply apps/explorer/lib/explorer/migrator/sanitize_verified_addresses.ex:134]: I think better to have it, if we'll need for some reasons reduce IOps to DB

Comment (fedor-ivn) [reply apps/explorer/lib/explorer/migrator/sanitize_verified_addresses.ex]: Alright then, processed in 11b5393c4eeaa73fb8291703279e3c8a5d141286

**Review by nikitosing — APPROVED** [review]

File: apps/explorer/lib/explorer/smart_contract/vyper/publisher.ex [hunk 9]
```diff
@@ -127,68 +126,8 @@ defmodule Explorer.SmartContract.Vyper.Publisher do
...
-          )
-
-        {:error, %{changeset | action: :insert}}
-
-      true ->
-        Logger.info("Publish successfully verified Vyper smart-contract #{address_hash} into the DB")
-
-        SmartContract.update_smart_contract(attrs, attrs.external_libraries, attrs.secondary_sources)
-    end
+    Logger.info("Publish successfully verified Vyper smart-contract #{address_hash} into the DB")
```
Comment (vbaranov) [inline apps/explorer/lib/explorer/smart_contract/vyper/publisher.ex:129]: Is this correct, that we log "successful publishing" message even if `SmartContract.create_or_update_smart_contract/3` function is not succeed?

Comment (fedor-ivn) [reply apps/explorer/lib/explorer/smart_contract/vyper/publisher.ex]: Good catch! Processed in cc98a6ad12bb458f5e1b3cb4294ed38a41cb7d69

**Review by vbaranov — APPROVED** [review]
