### PR TITLE
Fix state changes for contract creation transactions

### LINKED ISSUE #6442: Error on state changes tab for contract creation tx
https://blockscout.com/poa/sokol/tx/0x8b56275fce04cbbafabcdd722e80b943bced274a854d64c113eb90ff0aca0b55/state 

image

### PR DESCRIPTION
**Pull request by sl1depengwyn**
Fix #6442 

## Changelog

Add handling of `nil` `address`  in template
Moved address hash from comment to `<tr>` tag attribute

## Checklist for your Pull Request (PR)

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [x] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

### CODE REVIEW

File: apps/block_scout_web/lib/block_scout_web/controllers/transaction_state_controller.ex [hunk 1]
```diff
@@ -67,10 +67,11 @@ defmodule BlockScoutWeb.TransactionStateController do
       miner_hash = block.miner_hash
 
       from = transaction.from_address
```
Comment (vbaranov) [inline apps/block_scout_web/lib/block_scout_web/controllers/transaction_state_controller.ex:69]: Shouldn't definition of `from` here and `to` at line 88 be moved inside `if` statement since they also used only when `if` condition satisfied?

Comment (sl1depengwyn) [reply apps/block_scout_web/lib/block_scout_web/controllers/transaction_state_controller.ex]: Thanks for suggestion, make sense. Done

**Review by vbaranov — APPROVED** [review]

File: apps/block_scout_web/test/block_scout_web/controllers/transaction_state_controller_test.exs [hunk 2]
```diff
@@ -8,6 +8,7 @@ defmodule BlockScoutWeb.TransactionStateControllerTest do
   import EthereumJSONRPC, only: [integer_to_quantity: 1]
   alias Explorer.Chain.Wei
   alias EthereumJSONRPC.Blocks
+  alias Explorer.Factory
```
Comment (nikitosing) [inline apps/block_scout_web/test/block_scout_web/controllers/transaction_state_controller_test.exs:11]: Why did you add this alias? Logs from tests run:
```
2022-11-18T07:59:44.2671783Z 
2022-11-18T07:59:44.4216520Z warning: unused alias Blocks
2022-11-18T07:59:44.4217328Z ##[warning]  test/block_scout_web/controllers/transaction_state_controller_test.exs:10
2022-11-18T07:59:44.4218030Z 
2022-11-18T07:59:44.4250503Z warning: unused alias Factory
2022-11-18T07:59:44.4251198Z ##[warning]  test/block_scout_web/controllers/transaction_state_controller_test.exs:11
2022-11-18T07:59:44.4251835Z 
```

**Review by nikitosing — APPROVED** [review]

**Comment by nikitosing** [comment]
@sl1depengwyn why not to add `|> Enum.reject(&is_nil/1)` here https://github.com/blockscout/blockscout/pull/6473/files#diff-b89d6fbcaee2a35ef53a048f2c986f6af73b334169f12cfa652b7cb6506beabaR149 . Because now we just sending nulls to client, am I right?

**Review by nikitosing — CHANGES_REQUESTED** [review]
Please,
1. fix tests warnings
2. filter nulls in controller response

**Comment by sl1depengwyn** [comment]
> @sl1depengwyn why not to add `[from_coin_entry, to_coin_entry, miner_entry | items] |> Enum.reject(&is_nil/1)` here
> 
> https://github.com/blockscout/blockscout/blob/8fe51600c73103441515132a0e043365ccb1214c/apps/block_scout_web/lib/block_scout_web/controllers/transaction_state_controller.ex#L149
> 
> . Because now we just sending nulls to client, am I right? (In case of contract creation tx for example)

Thanks, fixed
https://github.com/blockscout/blockscout/blob/cc4c19bee4706903d841b9081f01a19e2c19f329/apps/block_scout_web/lib/block_scout_web/controllers/transaction_state_controller.ex#L148-L150

**Review by nikitosing — APPROVED** [review]
