### PR TITLE
Fix coin-balances/by-day bug

### LINKED ISSUE #4904: Coin balances history data: (Ecto.MultipleResultsError) expected at most one result but got 2 in query
```
Request: GET /address/0x0E43fDdeF032331736705400778FdC544Ce56162/coin-balances/by-day?type=JSON
** (exit) an exception was raised:
    ** (Ecto.MultipleResultsError) expected at most one result but got 2 in query:

from c0 in subquery(from c0 in Explorer.Chain.Address.CoinBalance,
  where: c0.address_hash == ^%Explorer.Chain.Hash{byte_count: 20, bytes: <<14, 67, 253, 222, 240, 50, 51, 23, 54, 112, 84, 0, 119, 143, 220, 84, 76, 229, 97, 98>>},
  order_by: [desc: c0.block_number],
  limit: 1,
  select: %{block_number: c0.block_number, value: c0.value}),
  join: b1 in Explorer.Chain.Block,
  on: c0.block_number == b1.number,
  select: %{timestamp: b1.timestamp, value: c0.value}

        (ecto 3.7.1) lib/ecto/repo/queryable.ex:149: Ecto.Repo.Queryable.one/3
        (explorer 0.0.1) lib/explorer/chain.ex:5857: Explorer.Chain.address_to_balances_by_day/1
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/address_coin_balance_by_day_controller.ex:16: BlockScoutWeb.AddressCoinBalanceByDayController.index/2
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/address_coin_balance_by_day_controller.ex:1: BlockScoutWeb.AddressCoinBalanceByDayController.action/2
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/address_coin_balance_by_day_controller.ex:1: BlockScoutWeb.AddressCoinBalanceByDayController.phoenix_controller_pipeline/2
        (phoenix 1.5.13) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (phoenix 1.5.13) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2
        (phoenix 1.5.13) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
```

### PR DESCRIPTION
**Pull request by nikitosing**
Close #4904 

### Bug Fixes
- Add check if block is `consensus` and just in case `limit: 1` in resulting query with join

## Checklist for your Pull Request (PR)

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

### CODE REVIEW

File: apps/explorer/lib/explorer/chain/address/coin_balance.ex [hunk 1]
```diff
@@ -178,6 +178,8 @@ defmodule Explorer.Chain.Address.CoinBalance do
       cb in subquery(coin_balance_query),
       inner_join: b in Block,
       on: cb.block_number == b.number,
+      where: b.consensus,
+      limit: 1,
```
Comment (vbaranov) [inline apps/explorer/lib/explorer/chain/address/coin_balance.ex:182]: Isn't this redundantly taking into account, that (address_hash, block_number) is a unique in `address_coin_balances` table?

Comment (nikitosing) [reply apps/explorer/lib/explorer/chain/address/coin_balance.ex:182]: No, when we joining the `coin_balance_query` with blocks table we take all rows where block_numbers matches. One block_number in `blocks` table could match several rows due to reorgs. Otherwise linked issue is impossible

Comment (vbaranov) [reply apps/explorer/lib/explorer/chain/address/coin_balance.ex:182]: I am about `limit: 1,`. I agree with `where: b.consensus,` clause

Comment (nikitosing) [reply apps/explorer/lib/explorer/chain/address/coin_balance.ex:182]: Just in DB we have no constraints on `block_number` and `consensus`. But I agree, remove this line?

Comment (vbaranov) [reply apps/explorer/lib/explorer/chain/address/coin_balance.ex:182]: Actually, we have `"one_consensus_block_at_height" UNIQUE, btree (number) WHERE consensus` contstraint on blocks table. Thus, I think `limit: 1` is redundant. Let's remove it.

Comment (nikitosing) [reply apps/explorer/lib/explorer/chain/address/coin_balance.ex:182]: Ok, thanks

**Review by vbaranov — APPROVED** [review]
