### PR TITLE
fix: Don't store ipfs gateway in metadata

### LINKED ISSUE #11149: NFT metadata image from `tokenURI` is fetched with `IPFS_GATEWAY_URL` prefix
## Description

`tokenURI` for an NFT instance contains a direct IPFS link to an image (`ipfs://QmaXmVr1LPzkYofpLEvNmBGUph8iPhA6WcTrFC6mzLLvsF`):

This resulted in an incorrect creation of the metadata JSON on the backend:
```
    "image_url": "_{IPFS_GATEWAY_URL}_QmaXmVr1LPzkYofpLEvNmBGUph8iPhA6WcTrFC6mzLLvsF",
    "is_unique": true,
    "metadata": {
        "image": "_{IPFS_GATEWAY_URL}_QmaXmVr1LPzkYofpLEvNmBGUph8iPhA6WcTrFC6mzLLvsF"
    }
```
### Expected result
```
    "image_url": "_{IPFS_PUBLIC_GATEWAY_URL}_QmaXmVr1LPzkYofpLEvNmBGUph8iPhA6WcTrFC6mzLLvsF",
    "is_unique": true,
    "metadata": {
        "image": "ipfs://QmaXmVr1LPzkYofpLEvNmBGUph8iPhA6WcTrFC6mzLLvsF"
    }
```

## Version
[v6.8.1-beta](https://github.com/blockscout/blockscout/tree/v6.8.1-beta)

### PR DESCRIPTION
**Pull request by nikitosing**
Closes #11149 

## Changelog
- In case smart contract returns `ipfs://{uid}` uri, which refers to image or video, now we store metadata like:
`{"image": "ipfs://{uid}"}` (previous variant: `{"image": "https://ipfs.io/ipfs/{uid}"}`)
## Checklist for your Pull Request (PR)

- [ ] If I added new functionality, I added tests covering it.
- [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
- [ ] I checked whether I should update the docs and did so by submitting a PR to [docs repository](https://github.com/blockscout/docs).
- [ ] If I added/changed/removed ENV var, I submitted a PR to [docs repository](https://github.com/blockscout/docs) to update the list of [env vars](https://github.com/blockscout/docs/blob/master/setup/env-variables/README.md) and I updated the version to `master` in the Version column. If I removed variable, I added it to [Deprecated ENV Variables](https://github.com/blockscout/docs/blob/master/setup/env-variables/deprecated-env-variables/README.md) page. After merging docs PR, changes will be reflected in these [pages](https://docs.blockscout.com/setup/env-variables).
- [ ] If I added new DB indices, I checked, that they are not redundant, with PGHero or other tools.
- [ ] If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

## Summary by CodeRabbit

- **New Features**
  - Enhanced handling of IPFS links for token metadata retrieval.
  - Improved construction and processing of public IPFS URLs.

- **Tests**
  - Added a test to ensure IPFS credentials are not exposed in metadata.
  - Updated test cases to ensure correct formatting of IPFS URLs in metadata.
  - Introduced a regression test for handling IPFS image URLs when fetching token instance metadata.

### CODE REVIEW

**Review by sl1depengwyn — APPROVED** [review]

**Review by fedor-ivn — COMMENTED** [review]
I guess this PR would conflict with changes from https://github.com/blockscout/blockscout/pull/11565, just a notice.

File: apps/block_scout_web/test/block_scout_web/controllers/api/v2/token_controller_test.exs [hunk 1]
```diff
@@ -1077,6 +1077,41 @@ defmodule BlockScoutWeb.API.V2.TokenControllerTest do
...
              } = json_response(request, 200)
     end
+
+    # https://github.com/blockscout/blockscout/issues/11149
+    test "regression for #11149", %{conn: conn} do
+      token = insert(:token, type: "ERC-721")
+
+      old_env = Application.get_env(:indexer, :ipfs)
+
+      public_ipfs_gateway = "https://ipfs.io/ipfs"
```
Comment (vbaranov) [inline apps/block_scout_web/test/block_scout_web/controllers/api/v2/token_controller_test.exs:1087]: Let's set a different from the default value here to ensure that the custom ipfs gateway URL is passed.

Comment (nikitosing) [reply apps/block_scout_web/test/block_scout_web/controllers/api/v2/token_controller_test.exs]: Good idea! 7b0b18cc70988d64843a57f182a7f8a7aea53ee3

**Review by vbaranov — APPROVED** [review]
