### PR TITLE
Csv export improve

### LINKED ISSUE #5009: CSV export: Error 504 when trying to export transactions
*Describe your issue here.*

### Environment
[blockscout.com](https://blockcout.com/)

### Steps to reproduce
Head to this link: https://blockscout.com/xdai/mainnet/transactions-csv?address_id=0xFCF8B0b0a9e2277347E7A42743ab7dEA8410764a&from_period=2020-09-01&to_period=2021-12-17

### Expected behaviour

*Tell us what should happen.*
Ability to export transactions without software timing out.

*Tell us what happens instead.*
Error 504 timeout

### PR DESCRIPTION
**Pull request by nikitosing**
Close #5009 

## Changelog
- Change all the paginated quries to query with limit 10_000
- Get rid of useless DB requests on CSV export
- Add new index for blocks table:
    plan on goerli after index:

        ```
              Result  (cost=4.13..4.14 rows=1 width=8) (actual time=0.037..0.038 rows=1 loops=1)
                      InitPlan 1 (returns $0)
                        ->  Limit  (cost=0.44..4.13 rows=1 width=8) (actual time=0.035..0.035 rows=0 loops=1)
                              ->  Index Scan Backward using blocks_date on blocks b0  (cost=0.44..169589.80 rows=45868 width=8) (actual time=0.034..0.035 rows=0 loops=1)
                                    Index Cond: ((date("timestamp") = to_date('2019-01-14'::text, 'YYYY-MM-DD'::text)) AND (number IS NOT NULL))
                    Planning Time: 0.195 ms
                    Execution Time: 0.056 ms
        ```

    plan on goerli before index:
        
        ```
        Result  (cost=26.48..26.49 rows=1 width=8) (actual time=4767.006..4767.007 rows=1 loops=1)
          InitPlan 1 (returns $0)
            ->  Limit  (cost=0.43..26.48 rows=1 width=8) (actual time=4767.002..4767.003 rows=1 loops=1)
                  ->  Index Scan Backward using blocks_number_index on blocks b0  (cost=0.43..1196276.63 rows=45923 width=8) (actual time=4767.001..4767.001 rows=1 loops=1)
                        Index Cond: (number IS NOT NULL)
                        Filter: (date("timestamp") = to_date('2023-05-14'::text, 'YYYY-MM-DD'::text))
                        Rows Removed by Filter: 170549
        Planning Time: 0.463 ms
        Execution Time: 4767.027 ms
        
        ```
## Checklist for your Pull Request (PR)

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

### CODE REVIEW

**Review by vbaranov — APPROVED** [review]

**Comment by vbaranov** [comment]
@nikitosing please rebase PR to master branch.

File: apps/explorer/priv/repo/migrations/20230615130940_add_blocks_date_index.exs
Comment (vbaranov) [inline apps/explorer/priv/repo/migrations/20230615130940_add_blocks_date_index.exs:1]: @nikitosing just for clarification, which query execution is improved with this index?

File: apps/explorer/lib/explorer/chain.ex [hunk 1]
```diff
@@ -636,23 +632,35 @@ defmodule Explorer.Chain do
...
+          order_by: [desc: log.block_number, desc: log.index],
+          where: log.address_hash == ^address_hash,
+          limit: ^paging_options.page_size,
+          select: log,
+          preload: [transaction: [to_address: :smart_contract]],
+          inner_join: block in Block,
+          on: block.hash == log.block_hash,
+          where: block.consensus
+        )
+      end
```
Comment (sl1depengwyn) [inline apps/explorer/lib/explorer/chain.ex:663]: Nitpick, what do you think to change this to something like the following:

```elixir
    base =
      from(log in Log,
        order_by: [desc: log.block_number, desc: log.index],
        where: log.address_hash == ^address_hash,
        limit: ^paging_options.page_size,
        select: log,
        inner_join: block in Block,
        on: block.hash == log.block_hash,
        where: block.consensus
      )

    base =
      unless csv_export? do
        base
        |> preload(transaction: [:to_address, :from_address])
      else
        base
      end

 ```

Comment (nikitosing) [reply apps/explorer/lib/explorer/chain.ex]: Processed

**Review by sl1depengwyn — APPROVED** [review]
