### PR TITLE
Optimize NFT owner preload

### LINKED ISSUE #8995: Token instance view: put owner address hash only if owner_address_hash is empty in token_instances table for this token instance
### Description

Currently, we put owner_address_hash from token_transfers and not checking if it already exists in token_instances table

https://github.com/blockscout/blockscout/blob/1d91e3030881d41705504ff75dac71dfc56934d1/apps/explorer/lib/explorer/chain.ex#L4284

Because of that, inventory page is lagging. An example:

https://base.blockscout.com/token/0xEa2a41c02fA86A4901826615F9796e603C6a4491
Screenshot 2023-12-13 at 12 33 52

We should go to token_transfers table for the owner only if owner_address_hash is empty in token_instances.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Any

### Type of the chain

_No response_

### Link to the page

https://base.blockscout.com/token/0xEa2a41c02fA86A4901826615F9796e603C6a4491

### Steps to reproduce

_No response_

### Backend version

v5.3.2

### Frontend version

_No response_

### Elixir & Erlang/OTP versions

Elixir 1.14.5

### Operating system

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by nikitosing**
Closes #8995 

## Changelog
- Optimize NFT owner preload

## Checklist for your Pull Request (PR)

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

### CODE REVIEW

File: apps/explorer/lib/explorer/chain/token/instance.ex [hunk 1]
```diff
@@ -26,7 +26,8 @@ defmodule Explorer.Chain.Token.Instance do
           owner_address_hash: Hash.Address.t(),
           owner_updated_at_block: Block.block_number(),
           owner_updated_at_log_index: non_neg_integer(),
-          current_token_balance: any()
+          current_token_balance: any(),
+          is_unique: bool()
```
Comment (sl1depengwyn) [inline apps/explorer/lib/explorer/chain/token/instance.ex:30]: Please, add `| nil`

File: apps/explorer/lib/explorer/chain.ex [hunk 2]
```diff
@@ -4269,27 +4269,40 @@ defmodule Explorer.Chain do
...
+  def put_owner_to_token_instance(%Instance{is_unique: nil} = token_instance, token, options) do
+    put_owner_to_token_instance(Instance.put_is_unique(token_instance, token, options), token, options)
+  end
+
+  def put_owner_to_token_instance(
+        %Instance{owner: nil, is_unique: true} = token_instance,
+        %Token{type: "ERC-1155"},
+        options
+      ) do
+    owner_address_hash =
```
Comment (sl1depengwyn) [inline apps/explorer/lib/explorer/chain.ex:4296]: Why we can't use `owner_address_hash` from instance?

**Review by sl1depengwyn — CHANGES_REQUESTED** [review]

File: apps/explorer/lib/explorer/chain.ex (hunk 2 above)
Comment (nikitosing) [reply apps/explorer/lib/explorer/chain.ex:4296]: `owner_address_hash` for ERC-1155 is nil

**Review by sl1depengwyn — APPROVED** [review]

**Review by vbaranov — APPROVED** [review]
