### PR TITLE
fix: filter out creation internal transaction with `index == 0`

### LINKED ISSUE #12757: Parent transactions showing in internal transactions
Current implementation of indexer stores internal transactions with `index: 0`, and it's possible to get such response even for ordinary contract creation transaction (`contractFactory` is the EOA which send creation tx):
```
{
message: "OK",
result: [
{
   blockNumber: "6080406",
   contractAddress: "0x278cd58b8691746f2deac1707884063892fc1e00",
   contractCreator: "0xbb36c792b9b45aaf8b848a1392b0d6559202729e",
   contractFactory: "0xbb36c792b9b45aaf8b848a1392b0d6559202729e",
   creationBytecode: "",
   timestamp: "1718045736",
   txHash: "0x16ba3dfd7e7b4c308d7e96067c5213bcb386151a3279402c17e4d97149e1fea9"
}
],
status: "1"
}
```
It's suggested to add `index > 0` condition and maybe sorting by `block_index` here:
https://github.com/blockscout/blockscout/blob/4fef19d21e9b2bd7d3f9d6ebf6622f9f0e200246/apps/explorer/lib/explorer/chain/address.ex#L803-L812
But I understand that it's not caused by this PR, so I think it's ok to do it in a separate one.

_Originally posted by @nikitosing in https://github.com/blockscout/blockscout/pull/12721#pullrequestreview-3001354766_

### PR DESCRIPTION
**Pull request by fedor-ivn**
Closes #12757.

- filter out transactions with `index == 0`
- apply additional sorting by `block_index`

## Checklist for your Pull Request (PR)

- [ ] If I added new functionality, I added tests covering it.
- [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
- [ ] I checked whether I should update the docs and did so by submitting a PR to [docs repository](https://github.com/blockscout/docs).
- [ ] If I added/changed/removed ENV var, I submitted a PR to [docs repository](https://github.com/blockscout/docs) to update the list of [env vars](https://github.com/blockscout/docs/blob/master/setup/env-variables/README.md) and I updated the version to `master` in the Version column. If I removed variable, I added it to [Deprecated ENV Variables](https://github.com/blockscout/docs/blob/master/setup/env-variables/deprecated-env-variables/README.md) page. After merging docs PR, changes will be reflected in these [pages](https://docs.blockscout.com/setup/env-variables).
- [ ] If I added new DB indices, I checked, that they are not redundant, with PGHero or other tools.
- [ ] If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved accuracy of contract creation information by filtering out internal transactions with index 0 and enhancing sorting criteria.
* **Tests**
  * Added a test to verify that contract creation via internal transactions with index 0 returns an empty "contractFactory" field in the API response.

### CODE REVIEW

**Review by nikitosing — APPROVED** [review]

File: apps/explorer/lib/explorer/chain/address.ex [hunk 1]
```diff
@@ -803,9 +803,11 @@ defmodule Explorer.Chain.Address do
   def contract_creation_internal_transaction_preload_query do
     from(
       it in InternalTransaction,
+      where: it.index > 0,
       order_by: [
         asc_nulls_first: it.error,
-        desc: it.block_number
+        desc: it.block_number,
+        desc: it.block_index
```
Comment (vbaranov) [inline apps/explorer/lib/explorer/chain/address.ex:811]: I'd suggest updating documentation of the function by reflecting that only index > 0 internal transactions are considered in this function.

Also, documentation already states even before changes that order by `3. block index (descending)` is applied. Was this a bug of documentation?

File: apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs [hunk 2]
```diff
@@ -1141,6 +1141,37 @@ defmodule BlockScoutWeb.API.RPC.ContractControllerTest do
...
+      insert(:internal_transaction_create,
+        transaction: transaction,
+        # index 0 should result in empty contractFactory
+        index: 0,
+        created_contract_address: contract_address,
+        block_hash: transaction.block_hash,
+        block_index: transaction.index
+      )
+
+      assert %{"result" => [%{"contractFactory" => ""}]} =
```
Comment (vbaranov) [inline apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs]: Does it make sense to additionally check that `ContractCreator` is not empty at the same time?

Comment (fedor-ivn) [reply apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs]: Good suggestion, thanks! Addressed in 3c5e54f99f92183ef6b45f730ac1ce21de9789b7.

File: apps/explorer/lib/explorer/chain/address.ex (hunk 1 above)
Comment (fedor-ivn) [reply apps/explorer/lib/explorer/chain/address.ex:811]: > I'd suggest updating documentation of the function by reflecting that only index > 0 internal transactions are considered in this function.

Good one, thanks. Addressed in 3c5e54f99f92183ef6b45f730ac1ce21de9789b7.

> Also, documentation already states even before changes that order by 3. block index (descending) is applied. Was this a bug of documentation?

Nope, this was indeed a bug of implementation 🙃

> Nikita Pozdniakov:
> can there be multiple internal transactions creating the same address?
> 
> Kirill Fedoseev:
> via create2 - yes, if you really want, you can do create2 - selfdestruct - create2 in one block.
