### PR TITLE
fix: change default ordering in `/api/v2/smart-contracts`

### LINKED ISSUE #12307: Incorrect default ordering for verified smart contract list
Page https://eth.blockscout.com/verified-contracts should be sorted by decreasing verification time by default, instead of being sorted by address hash. This is a regression introduced by https://github.com/blockscout/blockscout/pull/12060 .

Considering using `ORDER BY sc.id DESC` by default

### PR DESCRIPTION
**Pull request by fedor-ivn**
Closes #12307.

## Checklist for your Pull Request (PR)

- [ ] If I added new functionality, I added tests covering it.
- [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
- [ ] I checked whether I should update the docs and did so by submitting a PR to [docs repository](https://github.com/blockscout/docs).
- [ ] If I added/changed/removed ENV var, I submitted a PR to [docs repository](https://github.com/blockscout/docs) to update the list of [env vars](https://github.com/blockscout/docs/blob/master/setup/env-variables/README.md) and I updated the version to `master` in the Version column. If I removed variable, I added it to [Deprecated ENV Variables](https://github.com/blockscout/docs/blob/master/setup/env-variables/deprecated-env-variables/README.md) page. After merging docs PR, changes will be reflected in these [pages](https://docs.blockscout.com/setup/env-variables).
- [ ] If I added new DB indices, I checked, that they are not redundant, with PGHero or other tools.
- [ ] If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

## Summary by CodeRabbit

* **New Features**
  * Enhanced pagination and sorting options for the smart contracts list endpoint, including support for pagination by smart contract ID when no sorting is specified.

* **Bug Fixes**
  * Improved robustness in parsing pagination parameters for the smart contracts API.

* **Refactor**
  * Default sorting for verified smart contract addresses now uses smart contract ID when no explicit sorting is provided.
  * Improved clarity in sorting and pagination logic, including more explicit handling of sorting errors and query aliasing.
  * Updated paging parameter extraction to streamline next page URL generation.

* **Tests**
  * Updated test cases to reflect the new default sorting by smart contract ID, ensuring accurate pagination and ordering validation.

### CODE REVIEW

**Review by sl1depengwyn — APPROVED** [review]

File: apps/block_scout_web/lib/block_scout_web/controllers/api/v2/smart_contract_controller.ex [hunk 1]
```diff
@@ -124,12 +128,24 @@ defmodule BlockScoutWeb.API.V2.SmartContractController do
...
+    # If no sorting options are provided, we sort by `id` descending only. If
+    # there are some sorting options supplied, we sort by `:hash` ascending as a
+    # secondary key.
+    pager =
+      full_options
+      |> Keyword.get(:sorting)
+      |> if do
+        &smart_contract_addresses_paging_params/1
+      else
+        &%{smart_contract_id: &1.smart_contract.id}
```
Comment (k1rill-fedoseev) [inline apps/block_scout_web/lib/block_scout_web/controllers/api/v2/smart_contract_controller.ex:140]: Shouldn't it be? Otherwise `do_smart_contract_addresses_paging_options` wouldn't work?
```suggestion
        &%{"smart_contract_id" => &1.smart_contract.id}
```

**Review by vbaranov — APPROVED** [review]

File: apps/block_scout_web/lib/block_scout_web/controllers/api/v2/smart_contract_controller.ex (hunk 1 above)
Comment (fedor-ivn) [reply apps/block_scout_web/lib/block_scout_web/controllers/api/v2/smart_contract_controller.ex:140]: Paging _options_ come from GET query params, which is a string to string map. 

Paging _params_ can be atom to string map. Later, these atoms show up as strings when they are encoded to JSON.
