### PR TITLE
fix: search for long integers

### LINKED ISSUE #7641: Searching long integer value returns 500
Search for `27606393966689717254124294199939478533331961967491413693980084341759630764504`  https://eth-goerli.blockscout.com/ returns 500. We should return 400 or `no results`

### PR DESCRIPTION
**Pull request by fedor-ivn**
Closes #7641.

### Enhancements
A regression test for Bug fix.

### Bug Fixes

Add function for safe integers parsing

## Checklist for your Pull Request (PR)

  - [ ] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [x] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

### CODE REVIEW

File: apps/explorer/lib/explorer/chain/search.ex [hunk 1]
```diff
@@ -467,6 +470,20 @@ defmodule Explorer.Chain.Search do
...
+          {:ok, num}
+        else
+          {:error, "Integer is too large"}
+        end
+
+      _ ->
+        {:error, "Invalid integer"}
+    end
+  end
+
```
Comment (fedor-ivn) [inline apps/explorer/lib/explorer/chain/search.ex:486]: Should I leave it here or it would be usefull to put this function in some existing `Helper` module?

File: apps/explorer/lib/explorer/chain/search.ex [hunk 2]
```diff
@@ -484,8 +501,8 @@ defmodule Explorer.Chain.Search do
         )
 
       _ ->
-        case Integer.parse(term) do
-          {block_number, ""} ->
+        case safe_parse_integer(term) do
```
[the remark this answers is not in the document]
Comment (fedor-ivn) [reply apps/explorer/lib/explorer/chain/search.ex]: Yeah, good catch. Fixed in the new commit.

File: CHANGELOG.md [hunk 3]
```diff
@@ -17,6 +17,7 @@
 
 ### Features
 
+- [#9649](https://github.com/blockscout/blockscout/pull/9649) - Fix search for long integers
```
[the remark this answers is not in the document]
Comment (fedor-ivn) [reply CHANGELOG.md]: Oh, apologize.. I did it by accident

File: apps/explorer/lib/explorer/chain/search.ex (hunk 2 above)
[the remark this answers is not in the document]
Comment (k1rill-fedoseev) [reply apps/explorer/lib/explorer/chain/search.ex]: I think 0 should be treated as a valid block though, it's usually a genesis block of some sort - https://eth.blockscout.com/block/0

[the remark this answers is not in the document]
Comment (fedor-ivn) [reply apps/explorer/lib/explorer/chain/search.ex]: Right, my bad. Fixed in https://github.com/blockscout/blockscout/commit/c45ed3abebdefd295891f9b09cc529567d721e11

File: apps/explorer/lib/explorer/chain/search.ex (hunk 1 above)
Comment (nikitosing) [reply apps/explorer/lib/explorer/chain/search.ex]: yes, I think it might be useful to have this function in Explorer.Helper module. And also please replace string error messages by atom, since this function is for internal usage.

Comment (fedor-ivn) [reply apps/explorer/lib/explorer/chain/search.ex]: Ok, moved this function to `Explorer.Helper` in https://github.com/blockscout/blockscout/pull/9651/commits/cfd1d751a5fcce238dc1da0f724fb15aa8280bcc

File: apps/explorer/lib/explorer/helper.ex [hunk 4]
```diff
@@ -67,6 +69,35 @@ defmodule Explorer.Helper do
...
+        iex> safe_parse_block_number("0")
+        {:ok, 0}
+
+        iex> safe_parse_block_number("-1")
+        {:error, :negative_block_number}
+
+        iex> safe_parse_block_number("27606393966689717254124294199939478533331961967491413693980084341759630764504")
+        {:error, :too_big_block_number}
+  """
+  def safe_parse_block_number(string) do
```
Comment (vbaranov) [inline apps/explorer/lib/explorer/helper.ex:87]: We have other places in the application with the same pattern `Integer.parse(string)`, with the input which can be defined by the end-user, e.g. in the `paging_options` function. Taking this in mind, perhaps does it make sense to change the name of the function to more generic like `safe_parse_integer` and apply it there as well? Wdyt?

Comment (k1rill-fedoseev) [reply apps/explorer/lib/explorer/helper.ex:87]: Since we're parsing only non-negative integers, perhaps `safe_parse_non_negative_integer` would be a better choice then.

**Review by k1rill-fedoseev — APPROVED** [review]

**Review by vbaranov — APPROVED** [review]
