### PR TITLE
API and smart-contracts fixes

### LINKED ISSUE #7479: Empty response for read only function in case of complex output
image

```
struct Log {
        address from;
        bytes32[] topics;
        bytes data;
    }
    
    struct TransactionReceipt {
        bytes32 txHash;
        uint256 blockNumber;
        bytes32 blockHash;
        uint256 transactionIndex;
        address from;
        address to;
        uint256 gasUsed;
        bool status;
        Log[] logs;
    }

    function retrieve() public view returns (TransactionReceipt memory){
        bytes32[] memory b = new bytes32[](3);
        b[0] = bytes32("0x0");
        b[1] = bytes32("0x00112233");
        b[2] = bytes32("0x00112233123");
        Log memory log = Log(msg.sender, b, bytes("0x0000123123"));
        Log[] memory logs = new Log[](3);
        logs[0] = log;
        logs[1] = log;
        logs[2] = log;
        TransactionReceipt memory tx_ = TransactionReceipt(0xfe6a43fa23a0269092cbf97cb908e1d5a49a18fd6942baf2467fb5b221e39ab2, 1000,
         0xfe6a43fa23a0269092cbf97cb908e1d5a49a18fd6942baf2467fb5b221e39ab2, 10, msg.sender, msg.sender, 123123, true, logs);
         
        return tx_;
    }
```

But if we will force this function to be fetched via separate query it will be displayed ok:

image

### LINKED ISSUE #7480: Error on encoding function output API v2
The same code as in #7479 

```
curl --location 'http://localhost:4000/api/v2/smart-contracts/0xED26B086B840877a2579De4c70E9ab55587ce108/query-read-method?is_custom_abi=false' \
--header 'Content-Type: application/json' \
--data '{
    "method_id": "2e64cec1",
    "contract_type": "regular",
    "is_custom_abi": false,
    "args": [],
    "from": "0xbb36c792b9b45aaf8b848a1392b0d6559202729e"
}'
```

```
2023-05-14T23:40:46.387 [error] #PID<0.2577.0> running BlockScoutWeb.Endpoint (connection #PID<0.2576.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: POST /api/v2/smart-contracts/0xED26B086B840877a2579De4c70E9ab55587ce108/query-read-method?is_custom_abi=false
** (exit) an exception was raised:
    ** (Jason.EncodeError) invalid byte 0xFE in <<254, 106, 67, 250, 35, 160, 38, 144, 146, 203, 249, 124, 185, 8, 225, 213, 164, 154, 24, 253, 105, 66, 186, 242, 70, 127, 181, 178, 33, 227, 154, 178>>
        (jason 1.4.0) lib/jason.ex:213: Jason.encode_to_iodata!/2
        (phoenix 1.5.13) lib/phoenix/controller.ex:777: Phoenix.Controller.render_and_send/4
        (block_scout_web 5.1.4) lib/block_scout_web/controllers/api/v2/smart_contract_controller.ex:1: BlockScoutWeb.API.V2.SmartContractController.action/2
        (block_scout_web 5.1.4) lib/block_scout_web/controllers/api/v2/smart_contract_controller.ex:1: BlockScoutWeb.API.V2.SmartContractController.phoenix_controller_pipeline/2
        (phoenix 1.5.13) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (phoenix 1.5.13) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2
        (phoenix 1.5.13) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (phoenix 1.5.13) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2
        (phoenix 1.5.13) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (block_scout_web 5.1.4) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint.plug_builder_call/2
        (block_scout_web 5.1.4) /Users/nikitosing/work/blockscout/blockscout/deps/plug/lib/plug/debugger.ex:136: BlockScoutWeb.Endpoint."call (overridable 3)"/2
        (block_scout_web 5.1.4) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint."call (overridable 4)"/2
        (block_scout_web 5.1.4) /Users/nikitosing/work/blockscout/blockscout/deps/spandex_phoenix/lib/spandex_phoenix.ex:151: BlockScoutWeb.Endpoint.call/2
        (phoenix 1.5.13) lib/phoenix/endpoint/cowboy2_handler.ex:65: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.10.0) /Users/nikitosing/work/blockscout/blockscout/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.10.0) /Users/nikitosing/work/blockscout/blockscout/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.10.0) /Users/nikitosing/work/blockscout/blockscout/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 4.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

### LINKED ISSUE #7481: API v2: Error on encoding function output for read only function
Related to #7480 

http://localhost:4000/api/v2/smart-contracts/0xED26B086B840877a2579De4c70E9ab55587ce108/methods-read

```
2023-05-14T23:41:06.435 application=block_scout_web request_id=F18dLVw4R2HCz8gAADAh [warning] Error determining value json for "tuple": ** (Protocol.UndefinedError) protocol String.Chars not implemented for {<<254, 106, 67, 250, 35, 160, 38, 144, 146, 203, 249, 124, 185, 8, 225, 213, 164, 154, 24, 253, 105, 66, 186, 242, 70, 127, 181, 178, 33, 227, 154, 178>>, 1000, <<254, 106, 67, 250, 35, 160, 38, 144, 146, 203, 249, 124, 185, 8, 225, 213, 164, 154, 24, 253, 105, 66, 186, 242, 70, 127, 181, 178, 33, 227, 154, 178>>, 10, <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, 123123, true, [{<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, [<<48, 120, 48, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, <<48, 120, 48, 48, 49, 49, 50, 50, 51, 51, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, <<48, 120, 48, 48, 49, 49, 50, 50, 51, 51, 49, 50, 51, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>], "0x0000123123"}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, [<<48, 120, 48, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, <<48, 120, 48, 48, 49, 49, 50, 50, 51, 51, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, <<48, 120, 48, 48, 49, 49, 50, 50, 51, 51, 49, 50, 51, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>], "0x0000123123"}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, [<<48, 120, 48, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, <<48, 120, 48, 48, 49, 49, 50, 50, 51, 51, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, <<48, 120, 48, 48, 49, 49, 50, 50, 51, 51, 49, 50, 51, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>], "0x0000123123"}]} of type Tuple
    (elixir 1.14.4) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir 1.14.4) lib/string/chars.ex:22: String.Chars.to_string/1
    (block_scout_web 5.1.4) lib/block_scout_web/views/abi_encoded_value_view.ex:33: BlockScoutWeb.ABIEncodedValueView.value_json/2
    (block_scout_web 5.1.4) lib/block_scout_web/views/api/v2/smart_contract_view.ex:127: BlockScoutWeb.API.V2.SmartContractView.prepare_output/1
    (elixir 1.14.4) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (block_scout_web 5.1.4) lib/block_scout_web/views/api/v2/smart_contract_view.ex:121: BlockScoutWeb.API.V2.SmartContractView.prepare_read_function/1
    (elixir 1.14.4) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (phoenix 1.5.13) lib/phoenix/view.ex:472: Phoenix.View.render_to_iodata/3
    (phoenix 1.5.13) lib/phoenix/controller.ex:777: Phoenix.Controller.render_and_send/4
    (block_scout_web 5.1.4) lib/block_scout_web/controllers/api/v2/smart_contract_controller.ex:1: BlockScoutWeb.API.V2.SmartContractController.action/2
    (block_scout_web 5.1.4) lib/block_scout_web/controllers/api/v2/smart_contract_controller.ex:1: BlockScoutWeb.API.V2.SmartContractController.phoenix_controller_pipeline/2
    (phoenix 1.5.13) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
    (phoenix 1.5.13) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2
    (phoenix 1.5.13) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
    (phoenix 1.5.13) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2
    (phoenix 1.5.13) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
    (block_scout_web 5.1.4) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint.plug_builder_call/2
    (block_scout_web 5.1.4) /Users/nikitosing/work/blockscout/blockscout/deps/plug/lib/plug/debugger.ex:136: BlockScoutWeb.Endpoint."call (overridable 3)"/2
    (block_scout_web 5.1.4) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint."call (overridable 4)"/2
    (block_scout_web 5.1.4) /Users/nikitosing/work/blockscout/blockscout/deps/spandex_phoenix/lib/spandex_phoenix.ex:151: BlockScoutWeb.Endpoint.call/2
```

### PR DESCRIPTION
**Pull request by nikitosing**
Close #7479
Close #7480
Close #7481

## Changelog
- Fix read contract
- Add env for vyper evm versions
  - `CONTRACT_VERIFICATION_ALLOWED_EVM_VERSIONS` => `CONTRACT_VERIFICATION_ALLOWED_SOLIDITY_EVM_VERSIONS`
  - `CONTRACT_VERIFICATION_ALLOWED_VYPER_EVM_VERSIONS`
  - https://github.com/blockscout/docs/pull/162
- Add `icon_url` for tokens in `/search` response

## Checklist for your Pull Request (PR)

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

### CODE REVIEW

File: apps/block_scout_web/lib/block_scout_web/views/api/v2/smart_contract_view.ex [hunk 1]
```diff
@@ -118,13 +119,13 @@ defmodule BlockScoutWeb.API.V2.SmartContractView do
...
 
-        outputs = Enum.map(result["outputs"], &prepare_output/1)
+        outputs = result["outputs"] |> Enum.map(&prepare_output/1)
         Map.replace(result, "outputs", outputs)
     end
   end
 
-  defp prepare_output(%{"type" => type, "value" => value} = output) do
-    Map.replace(output, "value", ABIEncodedValueView.value_json(type, value))
+  defp prepare_output(%{"value" => value, "type" => type} = output) do
```
Comment (vbaranov) [inline apps/block_scout_web/lib/block_scout_web/views/api/v2/smart_contract_view.ex:127]: Is this required to change the order of keys in the map?

Comment (nikitosing) [reply apps/block_scout_web/lib/block_scout_web/views/api/v2/smart_contract_view.ex:127]: No, this change has no affect. Probably this change was caused by some copy-paste

**Review by vbaranov — APPROVED** [review]
