### PR TITLE
Fix false pending txs

### LINKED ISSUE #4348: Transactions included into reorgs are shown as pending
An example:

https://blockscout.com/poa/core/tx/0x16a5ea9f26b30fd796ade595168bc81d4b527f2f476d308a4db1f74d3b1ca4a9/internal-transactions

Screenshot 2021-07-07 at 13 26 00

The transaction is from this reorg https://blockscout.com/poa/core/blocks/0x0aa34cc2e2f3c4b6d09d88d793b93ef097420b8f62a978d82751d0494cf654d8/transactions

`
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x16a5ea9f26b30fd796ade595168bc81d4b527f2f476d308a4db1f74d3b1ca4a9"],"id":1}' https://core.poa.network
{"jsonrpc":"2.0","result":{"transactionHash":"0x16a5ea9f26b30fd796ade595168bc81d4b527f2f476d308a4db1f74d3b1ca4a9","transactionIndex":"0x0","blockHash":"0x0aa34cc2e2f3c4b6d09d88d793b93ef097420b8f62a978d82751d0494cf654d8","blockNumber":"0x11d1908","cumulativeGasUsed":"0x28ed3","gasUsed":"0x28ed3","from":"0xcf260ea317555637c55f70e55dba8d5ad8414cb0","to":"0x67e90a54aeea85f21949c645082fe95d77bc1e70","contractAddress":null,"logs":[],"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","status":"0x1","error":"","type":"0x0"},"id":1}%
`

### PR DESCRIPTION
**Pull request by nikitosing**
Close #4348 

### Bug Fixes
- Added else branch in `pending_transactions_sanitizer.ex/invalidate_block`
- Pending txs included in reorg blocks will marked as `dropped/replaced` via sanitizer

## Checklist for your Pull Request (PR)

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

### CODE REVIEW

File: apps/indexer/lib/indexer/pending_transactions_sanitizer.ex [hunk 1]
```diff
@@ -149,14 +150,23 @@ defmodule Indexer.PendingTransactionsSanitizer do
...
         timeout: 60_000,
         timestamps: %{updated_at: DateTime.utc_now()}
       }
 
       Blocks.lose_consensus(Repo, [], [number], [], opts)
+    else
+      changeset =
+        pending_tx
+        |> Transaction.changeset()
+        |> Changeset.put_change(:error, "dropped/replaced")
```
Comment (vbaranov) [inline apps/indexer/lib/indexer/pending_transactions_sanitizer.ex:165]: Let's do not put `dropped/replaced` error to a transaction if it was confirmed in the reorg. Instead, let's add `block_number` and `block_hash` of reorg to this transaction in order to remove it from pending list.

**Review by vbaranov — CHANGES_REQUESTED** [review]

File: apps/indexer/lib/indexer/pending_transactions_sanitizer.ex (hunk 1 above)
Comment (nikitosing) [reply apps/indexer/lib/indexer/pending_transactions_sanitizer.ex]: May be it is better to set `block_number` and `block_hash` of block which is not consensus? As I pushed 6 minutes ago

Comment (vbaranov) [reply apps/indexer/lib/indexer/pending_transactions_sanitizer.ex]: Yes, this is what I meant.

File: apps/indexer/lib/indexer/pending_transactions_sanitizer.ex [hunk 2]
```diff
@@ -149,14 +150,24 @@ defmodule Indexer.PendingTransactionsSanitizer do
     end
   end
 
-  defp invalidate_block(number, consensus) do
+  defp invalidate_block(number, consensus, pending_tx, block_hash) do
```
Comment (vbaranov) [inline apps/indexer/lib/indexer/pending_transactions_sanitizer.ex:153]: Just a nitpick: let's change the order of arguments of the method: block properties and then transaction: `block_number, block_hash, consensus, pending_tx`

**Review by vbaranov — COMMENTED** [review]
A nitpick regarding method arguments ordering.

**Review by vbaranov — APPROVED** [review]
