### PR TITLE
Fix token search

### LINKED ISSUE #4275: Token search gives incorrect results
Token search gives incorrect results. Search results contain irrelevant tokens. 

### Steps to reproduce
1. Navigate to Tokens https://blockscout.com/xdai/mainnet/tokens 
2. Search by token name, for example BZZ

### Expected behaviour
Search results should contain only tokens with BZZ name

### Actual behaviour
Search results contain irrelevant tokens

Screenshot at Jun 11 14-17-07

### PR DESCRIPTION
**Pull request by nikitosing**
Close #4275 

### Bug Fixes
- Fixed bug in updating list with the search results on `/tokens` page

## Checklist for your Pull Request (PR)

  - [ ] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

### CODE REVIEW

File: apps/block_scout_web/assets/js/pages/token/search.js [hunk 1]
```diff
@@ -25,7 +25,7 @@ export function reducer (state, action) {
 }
 
 if ($('[data-page="tokens"]').length) {
-  const store = createAsyncLoadStore(reducer, initialState, 'dataset.identifierLog')
+  const store = createAsyncLoadStore(reducer, initialState, 'childNodes[5].childNodes[1].childNodes[1].dataset.addressHash')
```
Comment (vbaranov) [inline apps/block_scout_web/assets/js/pages/token/search.js:28]: `childNodes[5].childNodes[1].childNodes[1].dataset.addressHash` looks complex. Could we set it to `dataset.identifierHash` as implemented for other items (for instance pending transactions list, transactions list, token transfers list etc) and correspondingly add `data-identifier-hash` to (bridged)token list items?

**Review by vbaranov — CHANGES_REQUESTED** [review]
I would suggest changing item identifier naming

**Review by vbaranov — APPROVED** [review]
