### PR TITLE
fix: Take into account empty arrays in Explorer.Migrator.SanitizeIncorectNFTTokenTransfers

### LINKED ISSUE #12271: Sanitizer of NFTs doesn't take into account empty arrays in `token_ids`, `amounts` columns
https://github.com/blockscout/blockscout/blob/82432afb65277634c1f3ef090a5e1193ab563b22/apps/explorer/lib/explorer/migrator/sanitize_incorrect_nft_token_transfers.ex#L124

We need to check against empty arrays as well:
```
eth_sepolia=> select count(*) from token_transfers where token_type='ERC-1155' and array_length(token_ids,1) is null and array_length(amounts,1) is null and amount is null;
 count 
-------
   171
(1 row)
```

### PR DESCRIPTION
**Pull request by nikitosing**
Closes #12271

## Changelog
- Add condition on empty array
- Restart `sanitize_incorrect_nft` migration from the `delete_erc_1155` step

## Checklist for your Pull Request (PR)

- [ ] I verified this PR does not break any public APIs, contracts, or interfaces that external consumers depend on.
- [ ] If I added new functionality, I added tests covering it.
- [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
- [ ] I updated documentation if needed:
  - [ ] General docs: submitted PR to [docs repository](https://github.com/blockscout/docs).
  - [ ] ENV vars: updated [env vars list](https://github.com/blockscout/docs/tree/main/setup/env-variables) and set version parameter to `master`.
  - [ ] Deprecated vars: added to [deprecated env vars list](https://github.com/blockscout/docs/tree/main/setup/env-variables/deprecated-env-variables).
- [ ] If I modified API endpoints, I updated the Swagger/OpenAPI schemas accordingly and checked that schemas are asserted in tests.
- [ ] If I added new DB indices, I checked, that they are not redundant, with PGHero or other tools.
- [ ] If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

## Summary by CodeRabbit

* **Bug Fixes**
  * Validation for ERC‑1155 NFT transfers now treats empty lists as empty values, reducing false-positive malformed records.
  * Corrective migration re-run to mark and reprocess affected steps, enabling cleanup of existing incorrect NFT transfer data.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: apps/explorer/priv/repo/migrations/20260114143222_re_run_sanitize_incorrect_nft_migration.exs [hunk 1]
```diff
@@ -0,0 +1,9 @@
+defmodule Explorer.Repo.Migrations.ReRunSanitizeIncorrectNftMigration do
+  use Ecto.Migration
+
+  def change do
+    execute(
+      "UPDATE migrations_status SET status = 'started', meta = '{\"step\": \"delete_erc_1155\"}' WHERE migration_name = 'sanitize_incorrect_nft'"
```
Comment (vbaranov) [inline apps/explorer/priv/repo/migrations/20260114143222_re_run_sanitize_incorrect_nft_migration.exs]: I suppose we don't want to jump to `delete_erc_1155` step, if migration is currently is in progress and on the previous step yet:
```suggestion
      "UPDATE migrations_status SET status = 'started', meta = '{\"step\": \"delete_erc_1155\"}' WHERE migration_name = 'sanitize_incorrect_nft' AND (meta IS NULL OR meta != '{\"step\": \"delete_erc_721\"}')"
```
