### PR TITLE
fix: extend block search range for `getblocknobytime` method

### LINKED ISSUE #9742: Extend block search range for 'getblocknobytime'
## Description

Currently `getblocknobytime` returns only blocks within 1 minute of a given timestamp. We need to extend this range to find any nearest block.

Example: https://arb-blueberry.gelatoscout.com/api?module=block&action=getblocknobytime&timestamp=1711552421&closest=before

## Version

[v6.3.0-beta](https://github.com/blockscout/blockscout/tree/v6.3.0-beta)

### PR DESCRIPTION
**Pull request by fedor-ivn**
Closes #9742.

### Enhancements

Regression test for Bug Fix

### Bug Fixes

Initially, the timestamp_to_block_number function filtered blocks to include only those with timestamps differing by no more than one minute from the given timestamp. This PR removes that filtering, allowing for an indefinite range of search. Testing on the Sepolia database shows that the new query performs similarly to the previous one with filtering in terms of execution time.

## Checklist for your Pull Request (PR)

- [ ] If I added new functionality, I added tests covering it.
- [x] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
- [ ] I checked whether I should update the docs and did so by submitting a PR to [docs repository](https://github.com/blockscout/docs).
- [ ] If I added/changed/removed ENV var, I submitted a PR to [docs repository](https://github.com/blockscout/docs) to update the list of [env vars](https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md) and I updated the version to `master` in the Version column. If I removed variable, I added it to [Deprecated ENV Variables](https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables/deprecated-env-variables/README.md) page. After merging docs PR, changes will be reflected in these [pages](https://docs.blockscout.com/for-developers/information-and-settings/env-variables).
- [ ] If I added new DB indices, I checked, that they are not redundant, with PGHero or other tools.
- [ ] If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

### CODE REVIEW

**Review by vbaranov — CHANGES_REQUESTED** [review]
This test is constantly failed from the branch:
```
mix test test/explorer/chain/transaction/history/historian_test.exs:19
```

```
  1) test compile_records/1 fetches transactions, total gas, total fee from blocks mined in the past num_days (Explorer.Chain.Transaction.History.HistorianTest)
     test/explorer/chain/transaction/history/historian_test.exs:19
     match (=) failed
     The following variables were pinned:
       expected = [%{date: ~D[1970-01-04], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[1970-01-03], gas_used: Decimal.new("83420"), number_of_transactions: 2, total_fee: Decimal.new("325510500000000")}]
     code:  assert {:ok, ^expected} = Historian.compile_records(2)
     left:  {:ok, ^expected}
     right: {
              :ok,
              [
                %{date: ~D[1970-01-04], gas_used: 0, number_of_transactions: 0, total_fee: 0},
                %{
                  date: ~D[1970-01-03],
                  gas_used: Decimal.new("181769"),
                  number_of_transactions: 3,
                  total_fee: Decimal.new("827090400000000")
                }
              ]
            }
     stacktrace:
       test/explorer/chain/transaction/history/historian_test.exs:60: (test)


Finished in 0.4 seconds (0.00s async, 0.4s sync)
4 tests, 1 failure, 3 excluded
```

File: apps/explorer/lib/explorer/chain.ex [hunk 1]
```diff
@@ -2500,38 +2500,32 @@ defmodule Explorer.Chain do
...
 
-    inner_query =
+    query =
       from(
         block in Block,
         where: block.consensus == true,
-        where:
-          fragment("? <= TO_TIMESTAMP(?, 'YYYY-MM-DD HH24:MI:SS') + (1 * interval '1 minute')", block.timestamp, ^t),
-        where:
-          fragment("? >= TO_TIMESTAMP(?, 'YYYY-MM-DD HH24:MI:SS') - (1 * interval '1 minute')", block.timestamp, ^t)
```
Comment (k1rill-fedoseev) [inline apps/explorer/lib/explorer/chain.ex:2529]: I've double-checked on the Ethereum Mainnet DB, this condition helped planner to use `blocks_timestamp_index` to reduce the search space to just a few blocks. Without it, planner suggests a seq scan over the full table, since it probably does not know how to use a btree index for queries like `abs(extract(epoch from (? - TO_TIMESTAMP(?, 'YYYY-MM-DD HH24:MI:SS'))))`. Seq scan query takes ~15-20 seconds on Ethereum Mainnet right now.

The following approach is much easier for planner to understand in my experiments though:
```sql
EXPLAIN SELECT *
FROM ((SELECT *
       FROM blocks
       WHERE consensus
         AND timestamp >= TO_TIMESTAMP(1690222354)
       ORDER BY timestamp ASC
       LIMIT 1)
      UNION ALL
      (SELECT *
       FROM blocks
       WHERE consensus
         AND timestamp <= TO_TIMESTAMP(1690222354)
       ORDER BY timestamp DESC
       LIMIT 1)) neighbours
ORDER BY ABS(EXTRACT(EPOCH FROM (timestamp - TO_TIMESTAMP(1690222354))))
LIMIT 1;
```

Wdyt about using something like it?

Comment (fedor-ivn) [reply apps/explorer/lib/explorer/chain.ex:2529]: Great suggestion, thank you so much. I should have better test the new query myself, as I suspected that the condition was introduced for a specific reason. I will implement your query in the code.

File: apps/explorer/test/explorer/chain/transaction/history/historian_test.exs [hunk 2]
```diff
@@ -18,14 +18,14 @@ defmodule Explorer.Chain.Transaction.History.HistorianTest do
   describe "compile_records/1" do
     test "fetches transactions, total gas, total fee from blocks mined in the past num_days" do
       blocks = [
+        # 1970-01-02 00:00:00
+        insert(:block, timestamp: DateTime.from_unix!(days_to_secs(1))),
```
Comment (k1rill-fedoseev) [inline apps/explorer/test/explorer/chain/transaction/history/historian_test.exs:22]: mix format fails
```suggestion
        insert(:block, timestamp: DateTime.from_unix!(days_to_secs(1)))
```

**Review by k1rill-fedoseev — APPROVED** [review]

File: apps/explorer/test/explorer/chain/transaction/history/historian_test.exs [hunk 3]
```diff
@@ -18,14 +18,14 @@ defmodule Explorer.Chain.Transaction.History.HistorianTest do
...
+
         # 1970-01-03 00:00:60
         insert(:block, timestamp: DateTime.from_unix!(days_to_secs(2) + 60)),
 
         # 1970-01-03 04:00:00
         insert(:block, timestamp: DateTime.from_unix!(days_to_secs(2) + 4 * 60 * 60)),
```
Comment (k1rill-fedoseev) [inline apps/explorer/test/explorer/chain/transaction/history/historian_test.exs]: mix format fails
```suggestion
        insert(:block, timestamp: DateTime.from_unix!(days_to_secs(2) + 4 * 60 * 60))
```

**Review by vbaranov — APPROVED** [review]
