### PR TITLE
Add parse input errors view; fix empty method_id

### LINKED ISSUE #4874: Add user friendly error displaying for the complex contract input
This issue will be actual after merging #4867 
image

### PR DESCRIPTION
**Pull request by nikitosing**
Close #4874 

### Enhancements
Add view for parse errors (appears in cases when input ABI type is `tuple[]`)

image

### Bug Fixes
- Fix emtpy method_id for cases when ABI type is `tuple[]` but actual type more complex

## Checklist for your Pull Request (PR)

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

### CODE REVIEW

File: apps/explorer/lib/explorer/smart_contract/reader.ex [hunk 1]
```diff
@@ -296,42 +296,11 @@ defmodule Explorer.SmartContract.Reader do
   end
 
   defp get_abi_with_method_id(abi) do
```
Comment (vbaranov) [inline apps/explorer/lib/explorer/smart_contract/reader.ex:298]: @nikitosing could you elaborate on the refactoring of this function?

**Review by vbaranov — APPROVED** [review]
