### PR TITLE
fix: internal transactions balance extraction

### LINKED ISSUE #12652: Revise `Indexer.Transform.AddressCoinBalances` for internal transactions
Other types should be taken into account, for instance, `create2`
https://github.com/blockscout/blockscout/blob/912ae87196bb6438ca63dae19b45c320f1e00762/apps/indexer/lib/indexer/transform/address_coin_balances.ex#L71-L94

### PR DESCRIPTION
**Pull request by sl1depengwyn**
Fix #12652

## Motivation
Less node calls for addresses that haven't changed the balance for sure and making sure that addresses that are needed to check balance update are extracted

## Checklist for your Pull Request (PR)

- [ ] If I added new functionality, I added tests covering it.
- [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
- [ ] I checked whether I should update the docs and did so by submitting a PR to [docs repository](https://github.com/blockscout/docs).
- [ ] If I added/changed/removed ENV var, I submitted a PR to [docs repository](https://github.com/blockscout/docs) to update the list of [env vars](https://github.com/blockscout/docs/blob/master/setup/env-variables/README.md) and I updated the version to `master` in the Version column. If I removed variable, I added it to [Deprecated ENV Variables](https://github.com/blockscout/docs/blob/master/setup/env-variables/deprecated-env-variables/README.md) page. After merging docs PR, changes will be reflected in these [pages](https://docs.blockscout.com/setup/env-variables).
- [ ] If I added new DB indices, I checked, that they are not redundant, with PGHero or other tools.
- [ ] If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

## Summary by CodeRabbit

- **Bug Fixes**
  - Improved accuracy in processing internal transactions by excluding errored transactions and refining which types and subtypes are handled for balance extraction.

- **Tests**
  - Added new tests to cover additional internal transaction scenarios, ensuring correct handling of various transaction types and error cases.
  - Updated existing tests for greater specificity and coverage.

### CODE REVIEW

File: apps/indexer/lib/indexer/transform/address_coin_balances.ex [hunk 1]
```diff
@@ -71,16 +71,18 @@ defmodule Indexer.Transform.AddressCoinBalances do
   defp internal_transactions_params_reducer(%{block_number: block_number} = internal_transaction_params, acc)
        when is_integer(block_number) do
     case internal_transaction_params do
-      %{type: "call"} = params ->
+      %{error: _} ->
```
Comment (sl1depengwyn) [inline apps/indexer/lib/indexer/transform/address_coin_balances.ex:74]: Any internal transaction with the error does not change the balances

File: apps/indexer/lib/indexer/transform/address_coin_balances.ex [hunk 2]
```diff
@@ -71,16 +71,18 @@ defmodule Indexer.Transform.AddressCoinBalances do
...
+        acc
+
+      %{type: "call", call_type: call_type} = params when call_type in ~w(call callcode) ->
```
Comment (sl1depengwyn) [inline apps/indexer/lib/indexer/transform/address_coin_balances.ex]: `staticcall` and `delegatecall` does not change the balance of neither from nor to addresses

File: apps/indexer/lib/indexer/transform/address_coin_balances.ex [hunk 3]
```diff
@@ -71,16 +71,18 @@ defmodule Indexer.Transform.AddressCoinBalances do
...
         acc
         |> process_internal_transaction_field(params, :from_address_hash, block_number)
         |> process_internal_transaction_field(params, :to_address_hash, block_number)
 
-      %{type: "create", error: _} ->
+      %{type: type} = params when type in ~w(create create2) ->
```
Comment (sl1depengwyn) [inline apps/indexer/lib/indexer/transform/address_coin_balances.ex:82]: `create2` can affect balances as well as `create`

File: apps/indexer/lib/indexer/transform/address_coin_balances.ex [hunk 4]
```diff
@@ -71,16 +71,18 @@ defmodule Indexer.Transform.AddressCoinBalances do
   defp internal_transactions_params_reducer(%{block_number: block_number} = internal_transaction_params, acc)
        when is_integer(block_number) do
     case internal_transaction_params do
-      %{type: "call"} = params ->
+      %{error: _} ->
+        acc
+
+      %{type: "call", call_type: call_type} = params when call_type in ~w(call callcode invalid) ->
```
Comment (nikitosing) [inline apps/indexer/lib/indexer/transform/address_coin_balances.ex]: wdyt if to add `value > 0` condition?

Comment (sl1depengwyn) [reply apps/indexer/lib/indexer/transform/address_coin_balances.ex]: seems that it's possible optimization, let's wait for an approval from other reviewers 

cc @k1rill-fedoseev @Qwerty5Uiop

File: apps/indexer/lib/indexer/transform/address_coin_balances.ex (hunk 3 above)
Comment (k1rill-fedoseev) [reply apps/indexer/lib/indexer/transform/address_coin_balances.ex:82]: +, both CREATE opcodes contain the value parameter, so balance can change for both sender address and the  created contract address

File: apps/indexer/lib/indexer/transform/address_coin_balances.ex (hunk 4 above)
Comment (k1rill-fedoseev) [reply apps/indexer/lib/indexer/transform/address_coin_balances.ex]: Balance of the address shouldn't change in a transaction if all address-related calls had value 0 in them. last time I check 96-97% of internal transactions were calls with zero value, so should be a nice efficiency boost.

I also double checked and `callcode` doesn't change balance, so we can skip it, although it's not used already by anyone for a long time.

I don't have a full picture on `invalid` call type though, or if we have any other chain-specific internal tx types that might change the balance on some specific instances.

File: apps/indexer/lib/indexer/transform/address_coin_balances.ex (hunk 1 above)
Comment (k1rill-fedoseev) [reply apps/indexer/lib/indexer/transform/address_coin_balances.ex:74]: It shouldn't, unless we have some errors that don't mean that the tx was reverted.

File: apps/indexer/lib/indexer/transform/address_coin_balances.ex (hunk 4 above)
Comment (sl1depengwyn) [reply apps/indexer/lib/indexer/transform/address_coin_balances.ex]: Addressed in 8c5ab6df0de906a42622398ea6a1000144babe1e
