### PR TITLE
fix: empty revert reasons in geth variant

### LINKED ISSUE #10147: Geth variant indexer incorrectly produces empty revert reasons
Revert reasons indexer on networks using Geth variant can incorrectly fetch an empty revert reason. Potential cause is [here](https://github.com/blockscout/blockscout/blob/f0f83d23d17a93aed94d66864d1dd40086ace001/apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth.ex#L413-L421), this piece of code deletes `output` field from the internal transaction whenever `error` is present in the JSON RPC response. Similar logic has been already reworked for Nethermind/Erigon variants, same should be done for Geth.

https://puppyscan.shib.io/tx/0x44cf0e3d46bd5312dcfe97c320e5699c4da7b9f5b06d26f503ceb02429633a91?tab=index
https://puppyscan.shib.io/tx/0x08b51ea9ec14a775d062a9c6c0221bc38bb0f7c18d359d1c42ed691228044ac6?tab=index

### PR DESCRIPTION
**Pull request by k1rill-fedoseev**
Closes #10147

## Checklist for your Pull Request (PR)

  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I added new DB indices, I checked, that they are not redundant with PGHero or other tools.
  - [ ] If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

### CODE REVIEW

File: apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth/call.ex [hunk 1]
```diff
@@ -318,154 +325,60 @@ defmodule EthereumJSONRPC.Geth.Call do
...
+       )
+       when type in ~w(call invalid) and call_type in ~w(call callcode delegatecall staticcall invalid) do
     %{
       block_number: block_number,
       transaction_index: transaction_index,
       transaction_hash: transaction_hash,
       index: index,
       trace_address: trace_address,
-      type: type,
+      type: "call",
```
Comment (vbaranov) [inline apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth/call.ex:352]: What is the purpose redefining Arbitrum's "invalid" type with "call"?

Comment (k1rill-fedoseev) [reply apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth/call.ex:352]: Hm, I haven't changed it on purpose, but I see that in the old code, cases for non-static calls had the same "call" value:
* https://github.com/blockscout/blockscout/pull/10243/files#diff-9aaf70b5fb91d6e3217cd85fee872a4d5df47d8cfd8fa098ce54f8c234a976bbL343
* https://github.com/blockscout/blockscout/pull/10243/files#diff-9aaf70b5fb91d6e3217cd85fee872a4d5df47d8cfd8fa098ce54f8c234a976bbL377

So it should behave in the same way as before

Comment (vbaranov) [reply apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth/call.ex:352]: Ah, you're right. This was done this way for the sake of not changing check constraint in the DB.

**Review by vbaranov — APPROVED** [review]
