### PR TITLE
fix: Return internal transactions for consensus blocks only in /api/v2/internal-transactions

### LINKED ISSUE #12765: Filter internal transactions by consensus=true
`api/v2/internal-transactions` endpoint returns internal transactions from reorg blocks

### PR DESCRIPTION
**Pull request by vbaranov**
## Motivation

Resolves https://github.com/blockscout/blockscout/issues/12765

### AI Agent summary

This pull request updates how internal transactions are filtered to ensure only those associated with consensus blocks or transactions are returned. It introduces a new filtering function and adds corresponding tests to verify this behavior.

### Filtering logic improvements

* Added the `where_consensus_transactions/1` function to `Explorer.Chain.InternalTransaction`, which filters internal transactions based on consensus status. The filter adapts depending on whether transaction denormalization has finished, checking either the transaction or block consensus flag.
* Integrated the new consensus filter into the main query pipeline for internal transactions, ensuring that only consensus transactions are included in results.

### Testing updates

* Added a test to `Explorer.Chain.InternalTransactionTest` that verifies only consensus transactions are returned by `fetch/1`. The test creates both consensus and non-consensus blocks/transactions and asserts the correct filtering.

## Checklist for your Pull Request (PR)

- [ ] If I added new functionality, I added tests covering it.
- [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
- [ ] I checked whether I should update the docs and did so by submitting a PR to [docs repository](https://github.com/blockscout/docs).
- [ ] If I added/changed/removed ENV var, I submitted a PR to [docs repository](https://github.com/blockscout/docs) to update the list of [env vars](https://github.com/blockscout/docs/blob/master/setup/env-variables/README.md) and I updated the version to `master` in the Version column. If I removed variable, I added it to [Deprecated ENV Variables](https://github.com/blockscout/docs/blob/master/setup/env-variables/deprecated-env-variables/README.md) page. After merging docs PR, changes will be reflected in these [pages](https://docs.blockscout.com/setup/env-variables).
- [ ] If I added new DB indices, I checked, that they are not redundant, with PGHero or other tools.
- [ ] If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

## Summary by CodeRabbit

* **Bug Fixes**
  * Internal transactions now only include those tied to consensus (finalized) blocks.

* **New Features**
  * Added an option to exclude zero-value internal transfers so call-type zero transfers can be hidden.

* **Refactor**
  * Streamlined query and filtering to reliably restrict results to consensus transactions.

* **Tests**
  * Added/updated tests validating consensus-only filtering and zero-value exclusion behavior.

### CODE REVIEW

File: apps/explorer/lib/explorer/chain/internal_transaction.ex [hunk 1]
```diff
@@ -992,6 +993,19 @@ defmodule Explorer.Chain.InternalTransaction do
...
+    if DenormalizationHelper.transactions_denormalization_finished?() do
+      query
+      |> join(:inner, [internal_transaction], transaction in assoc(internal_transaction, :transaction))
+      |> where([_internal_transaction, transaction], transaction.block_consensus == true)
+    else
+      query
+      |> join(:inner, [internal_transaction], transaction in assoc(internal_transaction, :transaction))
+      |> join(:inner, [transaction], block in assoc(transaction, :block))
+      |> where([_internal_transaction, _transaction, block], block.consensus == true)
+    end
```
Comment (sl1depengwyn) [inline apps/explorer/lib/explorer/chain/internal_transaction.ex]: Why we can't join block directly?

Comment (vbaranov) [reply apps/explorer/lib/explorer/chain/internal_transaction.ex]: We definitely can. Processed in https://github.com/blockscout/blockscout/pull/13041/commits/6c62f47bc4896f7cfb17cf14fc1050e7f5972808.

**Review by sl1depengwyn — APPROVED** [review]

File: apps/explorer/lib/explorer/chain/internal_transaction.ex [hunk 2]
```diff
@@ -992,6 +993,19 @@ defmodule Explorer.Chain.InternalTransaction do
     %{"block_index" => block_index}
```
Comment (Phum7895) [inline apps/explorer/lib/explorer/chain/internal_transaction.ex]: 0xB3C3ECD0FC348e61808660B5a6eB2DE80d2494D1
l
