### PR TITLE
fix: Handle stalled async task in MapCache

### LINKED ISSUE #10787: Gas tracker update stalling on Neon
## Description

In the past week gas tracker update stalled 2 times on https://neon.blockscout.com/
@sl1depengwyn conducted preliminary investigation and found a DB issue with a possible race condition.

## Version

[v6.8.0-beta](https://github.com/blockscout/blockscout/tree/v6.8.0-beta)

### LINKED ISSUE #11026: Block count cache stalling leading to outdated indexing banner

### PR DESCRIPTION
**Pull request by sl1depengwyn**
Fix #10787
Fix #11026

## Changelog

Check if async task in cache executes at the moment, delete it from cache and create a new one otherwise

## Checklist for your Pull Request (PR)

- [ ] If I added new functionality, I added tests covering it.
- [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
- [ ] I checked whether I should update the docs and did so by submitting a PR to [docs repository](https://github.com/blockscout/docs).
- [ ] If I added/changed/removed ENV var, I submitted a PR to [docs repository](https://github.com/blockscout/docs) to update the list of [env vars](https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md) and I updated the version to `master` in the Version column. If I removed variable, I added it to [Deprecated ENV Variables](https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables/deprecated-env-variables/README.md) page. After merging docs PR, changes will be reflected in these [pages](https://docs.blockscout.com/for-developers/information-and-settings/env-variables).
- [ ] If I added new DB indices, I checked, that they are not redundant, with PGHero or other tools.
- [ ] If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

### CODE REVIEW

**Review by Qwerty5Uiop — APPROVED** [review]

File: apps/explorer/lib/explorer/chain/map_cache.ex [hunk 1]
```diff
@@ -201,6 +201,35 @@ defmodule Explorer.Chain.MapCache do
...
+            end
+
+          not_pid ->
+            not_pid
+        end
+      end
+
+      def set_async_task(value), do: set(:async_task, value)
+
+      def update_async_task(value), do: update(:async_task, value)
```
Comment (vbaranov) [inline apps/explorer/lib/explorer/chain/map_cache.ex:229]: Where do we use `update_async_task/1` function?

Comment (sl1depengwyn) [reply apps/explorer/lib/explorer/chain/map_cache.ex:229]: It's not used as far as I see, but it's created for every key in MapCache, so I think it should be created for async_task as well

**Review by vbaranov — APPROVED** [review]
