### PR TITLE
fix: Fix UTF-8 json handling in NFT metadata fetching

### LINKED ISSUE #9696: Parse metadata from data:application/json ... in tokenURI
https://base.blockscout.com/token/0xB5C457dDB4cE3312a6C5a2b056a1652bd542a208?tab=read_contract

tokenId: `300067000000000000`

tokenURI returns:
```
[ tokenURI method response ]

[

  string (string) : data:application/json;utf8,{"name": "OMNI404 #300067000000000000","description":"The frontier of permissionless assets.","external_url":"https://twitter.com/omnichain404","image":"https://ipfs.io/ipfs/QmU6DGXciSZXTH1fUKkEqj74P8FeXPRKxSTjgRsVKUQa95/base/300067000000000000.JPG"}

]
```

Blockscout should be able to parse metadata:
```
{"name": "OMNI404 #300067000000000000","description":"The frontier of permissionless assets.","external_url":"https://twitter.com/omnichain404","image":"https://ipfs.io/ipfs/QmU6DGXciSZXTH1fUKkEqj74P8FeXPRKxSTjgRsVKUQa95/base/300067000000000000.JPG"}
```

Currently, it parses with error

https://base.blockscout.com/api/v2/tokens/0xB5C457dDB4cE3312a6C5a2b056a1652bd542a208/instances/300067000000000000

```
{"animation_url":null,"external_app_url":null,"id":"300067000000000000","image_url":null,"is_unique":true,"metadata":{"error":"data:application/json;utf8,{\"name\": \"OMNI404 #300067000000000000\",\"description\":\"The frontier of permissionless assets.\",\"external_url\":\"https://twitter.com/omnichain404\",\"image\":\"https://ipfs.io/ipfs/QmU6DGXciSZXTH1fUKkEqj74P8FeXPRKxSTjgRsVKUQa95/base/300067000000000000.JPG\"}"},"owner":{"ens_domain_name":null,"hash":"0x0000000000000000000000000000000000000000","implementation_name":null,"is_contract":false,"is_verified":null,"name":null,"private_tags":[],"public_tags":[],"watchlist_names":[]},"token":{"address":"0xB5C457dDB4cE3312a6C5a2b056a1652bd542a208","circulating_market_cap":"0.0","decimals":"18","exchange_rate":"1484.13","holders":"81","icon_url":null,"name":"OMNI404","symbol":"O404","total_supply":"6482275000000000000","type":"ERC-404","volume_24h":"793.6602047726305"}}
```

### PR DESCRIPTION
**Pull request by nikitosing**
Closes #9696 

## Changelog
- Fix UTF-8 json handling in NFT metadata fetching
- Add clause for ERC-404 in `Indexer.Fetcher.TokenInstance.Helper.prepare_request/4`
## Checklist for your Pull Request (PR)

  - [ ] If I added new functionality, I added tests covering it.
  - [x] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

### CODE REVIEW

**Review by sl1depengwyn — APPROVED** [review]

File: apps/indexer/lib/indexer/fetcher/token_instance/metadata_retriever.ex [hunk 1]
```diff
@@ -85,6 +85,19 @@ defmodule Indexer.Fetcher.TokenInstance.MetadataRetriever do
     fetch_metadata_inner(token_uri, token_id, hex_token_id, from_base_uri?)
   end
 
+  defp fetch_json_from_uri({:ok, ["data:application/json;utf8," <> json]}, token_id, hex_token_id, from_base_uri?) do
+    decoded_json = URI.decode(json)
```
Comment (vbaranov) [inline apps/indexer/lib/indexer/fetcher/token_instance/metadata_retriever.ex:89]: The logic of the clause is identical to the clause below. Could we extract it to a private function and re-use it in those 2 clauses?

Comment (nikitosing) [reply apps/indexer/lib/indexer/fetcher/token_instance/metadata_retriever.ex]: Good suggestion, processed in 9ddb6bdae1313b046f72311d5b31dc1eed4b64db

**Review by vbaranov — APPROVED** [review]
