### PR TITLE
fix: duplicates of smart contracts additional sources

### LINKED ISSUE #11864: Duplicates of smart-contracts additional source codes
```
eth_mainnet=> SELECT COUNT(distinct q.address_hash) FROM (SELECT address_hash, file_name, count(*) FROM public.smart_contracts_additional_sources GROUP BY address_hash, file_name HAVING COUNT(
*) > 1) q;
 count 
-------
  1979
(1 row)

dai=# SELECT COUNT(distinct q.address_hash) FROM (SELECT address_hash, file_name, count(*) FROM public.smart_contracts_additional_sources GROUP BY address_hash, file_name HAVING COUNT(*) > 1) 
q;
 count 
-------
   229
(1 row)

optimism_mainnet=# SELECT COUNT(distinct q.address_hash) FROM (SELECT address_hash, file_name, count(*) FROM public.smart_contracts_additional_sources GROUP BY address_hash, file_name HAVING COUNT(*) > 1) q;
 count 
-------
     5
(1 row)
```

Side effect of this is source code editor crash in UI.

### PR DESCRIPTION
**Pull request by fedor-ivn**
Closes #11864.

## Changelog

This PR fixes an issue with duplicate smart contract additional sources by implementing database constraints and streamlining the smart contract update process to be more atomic and consistent.

- Adds a unique database index to prevent duplicate secondary source files per contract
- Makes smart contract updates atomic within transactions to maintain data consistency
- Migrates existing data to remove duplicates before applying the constraint

## Checklist for your Pull Request (PR)

- [ ] If I added new functionality, I added tests covering it.
- [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
- [ ] I checked whether I should update the docs and did so by submitting a PR to [docs repository](https://github.com/blockscout/docs).
- [ ] If I added/changed/removed ENV var, I submitted a PR to [docs repository](https://github.com/blockscout/docs) to update the list of [env vars](https://github.com/blockscout/docs/blob/master/setup/env-variables/README.md) and I updated the version to `master` in the Version column. If I removed variable, I added it to [Deprecated ENV Variables](https://github.com/blockscout/docs/blob/master/setup/env-variables/deprecated-env-variables/README.md) page. After merging docs PR, changes will be reflected in these [pages](https://docs.blockscout.com/setup/env-variables).
- [ ] If I added new DB indices, I checked, that they are not redundant, with PGHero or other tools.
- [ ] If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

## Summary by CodeRabbit

* **Bug Fixes**
  * Prevents duplicate smart contract source entries by enforcing uniqueness on address + file name and sanitizing existing duplicates.
  * Makes contract updates atomic and consistent, ensuring contract, address-name state, and secondary sources are updated together under lock.

* **Refactor**
  * Reworked update flow into a transactional, lock-protected multi-step process for improved reliability.

* **Chores**
  * Added background migrators and a heavy DB index operation; wired into startup/config for indexer mode.

* **Tests**
  * Added tests validating duplicate cleanup and no-op behavior when none exist.

### CODE REVIEW

File: apps/explorer/priv/repo/migrations/20250817195213_create_smart_contract_additional_sources_unique_index.exs [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+    """
+
+    execute(delete_duplicates)
+
+    create(
+      unique_index(
+        :smart_contracts_additional_sources,
+        [:address_hash, :file_name],
+        concurrently: true
+      )
```
Comment (nikitosing) [inline apps/explorer/priv/repo/migrations/20250817195213_create_smart_contract_additional_sources_unique_index.exs]: do you think this won't produce a noticeable downtime while installing?

File: apps/explorer/priv/repo/migrations/20250817195213_create_smart_contract_additional_sources_unique_index.exs [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+    WHERE id IN (
+      SELECT id
+      FROM (
+        SELECT id,
+               ROW_NUMBER() OVER (PARTITION BY address_hash, file_name ORDER BY id) as row_number
+        FROM smart_contracts_additional_sources
+      ) t
+      WHERE t.row_number > 1
+    )
+    """
```
Comment (nikitosing) [inline apps/explorer/priv/repo/migrations/20250817195213_create_smart_contract_additional_sources_unique_index.exs]: I checked this query with select for OP mainnet (4m+ verified contracts), and it gives a ~3 minutes execution time, which will lead to downtime. Let's move it to async part, or discuss internally if this downtime will be ok?

```
Hash Semi Join  (cost=1596523.44..1767594.99 rows=1575737 width=0) (actual time=158923.528..165311.961 rows=23500 loops=1)
  Hash Cond: (smart_contracts_additional_sources.id = t.id)
  ->  Index Only Scan using smart_contracts_additional_sources_pkey on smart_contracts_additional_sources  (cost=0.43..139163.31 rows=4727211 width=8) (actual time=0.014..7701.145 rows=4883836 loops=1)
        Heap Fetches: 61748
  ->  Hash  (cost=1576826.29..1576826.29 rows=1575737 width=8) (actual time=156602.497..156602.509 rows=23500 loops=1)
        Buckets: 2097152  Batches: 1  Memory Usage: 17302kB
        ->  Subquery Scan on t  (cost=1411373.91..1576826.29 rows=1575737 width=8) (actual time=148101.271..156588.346 rows=23500 loops=1)
              Filter: (t.row_number > 1)
              Rows Removed by Filter: 4860336
              ->  WindowAgg  (cost=1411373.91..1517736.15 rows=4727211 width=80) (actual time=148096.861..156342.039 rows=4883836 loops=1)
                    ->  Sort  (cost=1411373.91..1423191.93 rows=4727211 width=72) (actual time=148096.748..153512.947 rows=4883836 loops=1)
                          Sort Key: smart_contracts_additional_sources_1.address_hash, smart_contracts_additional_sources_1.file_name, smart_contracts_additional_sources_1.id
                          Sort Method: external merge  Disk: 394832kB
                          ->  Seq Scan on smart_contracts_additional_sources smart_contracts_additional_sources_1  (cost=0.00..693409.11 rows=4727211 width=72) (actual time=194.186..132666.503 rows=4883836 loops=1)
Planning Time: 54.130 ms
JIT:
  Functions: 13
  Options: Inlining true, Optimization true, Expressions true, Deforming true
  Timing: Generation 0.713 ms, Inlining 66.721 ms, Optimization 98.407 ms, Emission 27.738 ms, Total 193.578 ms
Execution Time: 165390.062 ms
```

File: apps/explorer/config/config.exs [hunk 3]
```diff
@@ -168,7 +168,8 @@ for index_operation <- [
       Explorer.Migrator.HeavyDbIndexOperation.CreateLogsDepositsWithdrawalsIndex,
       Explorer.Migrator.HeavyDbIndexOperation.CreateAddressesTransactionsCountDescPartialIndex,
       Explorer.Migrator.HeavyDbIndexOperation.CreateAddressesTransactionsCountAscCoinBalanceDescHashPartialIndex,
-      Explorer.Migrator.HeavyDbIndexOperation.CreateInternalTransactionsBlockHashTransactionIndexIndexUniqueIndex
+      Explorer.Migrator.HeavyDbIndexOperation.CreateInternalTransactionsBlockHashTransactionIndexIndexUniqueIndex,
+      Explorer.Migrator.HeavyDbIndexOperation.CreateSmartContractAdditionalSourcesUniqueIndex
     ] do
```
[the remark this answers is not in the document]
Comment (fedor-ivn) [reply apps/explorer/config/config.exs:174]: it's already there:

```
  @impl HeavyDbIndexOperation
  def dependent_from_migrations,
    do: [SanitizeDuplicateSmartContractAdditionalSources.migration_name()]
```

File: apps/explorer/priv/repo/migrations/20250817195213_create_smart_contract_additional_sources_unique_index.exs (hunk 1 above)
Comment (fedor-ivn) [reply apps/explorer/priv/repo/migrations/20250817195213_create_smart_contract_additional_sources_unique_index.exs]: Right, it might do that. Thus, I've moved both index creation and sanitize query to our background migrations mechanism.

File: apps/explorer/priv/repo/migrations/20250817195213_create_smart_contract_additional_sources_unique_index.exs (hunk 2 above)
Comment (fedor-ivn) [reply apps/explorer/priv/repo/migrations/20250817195213_create_smart_contract_additional_sources_unique_index.exs]: > Let's move it to async part

Processed in https://github.com/blockscout/blockscout/pull/13018/commits/9df5c1e93d987fe4a3ec5bb0ad8d71279371d476

**Review by nikitosing — APPROVED** [review]
